#!/usr/bin/env node
// ── Render Phase 6C4B2 documents from artifacts ─────────────────────────────
//   npm run v6:report
// Formats only. Every number is read from the artifact that produced it.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists } from "../../src/v3/calibration/artifacts.js";
import { DIR } from "./preflight6c4b2.mjs";

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const has = (n) => artifactExists(n, DIR);
const R = (n) => readArtifact(n, DIR);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run v6:report  from: ${a.generationCommand} -->\n`;
const yn = (b) => (b ? "**yes**" : "**no**");

if (import.meta.url === `file://${process.argv[1]}`) {
  if (has("phase6c4b2-preflight")) {
    const A = R("phase6c4b2-preflight"); const d = A.data;
    write("phase-6c4b2-preflight.md", `${prov(A)}# Phase 6C4B2 — formal-execution preflight

**\`formalExecutionMayBegin: ${d.formalExecutionMayBegin}\`** · holdouts opened: Historical V5 ${d.holdoutsOpenedInThisPhase.historicalV5}, Synthetic V2 ${d.holdoutsOpenedInThisPhase.syntheticV2}

| preflight fact | value |
| --- | --- |
| candidate1LockValid | ${yn(d.candidate1LockValid)} |
| candidate1CoreStable | ${yn(d.candidate1CoreStable)} |
| candidate1ReplayValid | ${yn(d.candidate1ReplayValid)} |
| candidate0Preserved | ${yn(d.candidate0Preserved)} |
| historicalV5SealValid | ${yn(d.historicalV5SealValid)} |
| historicalV5AccessCount | ${d.historicalV5AccessCount} |
| historicalV5PackageValid | ${yn(d.historicalV5PackageValid)} |
| syntheticV2SealValid | ${yn(d.syntheticV2SealValid)} |
| syntheticV2AccessCount | ${d.syntheticV2AccessCount} |
| syntheticV2PackageCompatible | ${yn(d.syntheticV2PackageCompatible)} |
| historicalV3Preserved | ${yn(d.historicalV3Preserved)} |
| historicalV4Preserved | ${yn(d.historicalV4Preserved)} |

Gates failed: ${d.gatesFailed.length ? d.gatesFailed.map((g) => `\`${g}\``).join(", ") : "none"}

## Candidate 1, as verified

| fact | value |
| --- | --- |
| candidate | \`${d.candidate.candidateId}\` (lock revision ${d.candidate.lockRevision}) |
| commit | \`${d.candidate.candidateCommit}\` |
| core hash | \`${d.candidate.coreHash}\` |
| parameter-set hash | \`${d.candidate.parameterSetHash}\` |
| possessionCalibrationVersion | ${d.candidate.possessionCalibrationVersion} |
| calibration status | ${d.candidate.calibrationStatus} |
| formal validation status | ${d.candidate.formalValidationStatus} |

## Historical Holdout V5 — package verified, not opened

State **${d.historicalV5.state}**, access count **${d.historicalV5.accessCount}**, hash mismatches **${d.historicalV5.hashMismatches.length}**,
dry-run checks ${d.historicalV5.dryRunChecks}, runner \`${d.historicalV5.runnerModule}\`.

Every hash below was cross-checked between its producing artifact, the V5 seal, and the Phase 6C4B2 package:

${Object.entries(d.historicalV5.boundHashes).map(([k, v]) => `- \`${k}\` — \`${v}\``).join("\n")}

## Synthetic Stress Holdout V2 — package incomplete

State ${d.syntheticV2.state}, access count ${d.syntheticV2.accessCount}, ${d.syntheticV2.fixtureCount} fixtures.

| component | present | detail |
| --- | --- | --- |
${Object.entries(d.syntheticV2.components).map(([k, v]) => `| ${k} | ${v.present ? "yes" : "**NO**"} | ${v.detail} |`).join("\n")}

Missing: ${d.syntheticV2.missingComponents.map((m) => `\`${m}\``).join(", ")}

## Prior holdouts, preserved

| set | state | access | verdict | failure class | candidate |
| --- | --- | ---: | --- | --- | --- |
${Object.entries(d.priorHoldouts).map(([k, v]) => `| \`${k}\` | ${v.state} | ${v.accessCount} | ${v.verdict} | \`${v.failureClass}\` | ${v.candidate} |`).join("\n")}

## Every seal

| set | status | access count |
| --- | --- | ---: |
${Object.entries(d.allSeals).map(([k, v]) => `| \`${k}\` | ${v.status} | ${v.accessCount} |`).join("\n")}`);
  }

  if (has("synthetic-v2-package-blocker")) {
    const A = R("synthetic-v2-package-blocker"); const d = A.data;
    write("synthetic-v2-package-blocker.md", `${prov(A)}# \`${d.blockerId}\`

**${d.summary}**

Detected in Phase ${d.detectedInPhase}, before any holdout access: ${yn(d.detectedBeforeAnyHoldoutAccess)}.
Severity: \`${d.severity}\`.

Holdouts opened in that phase: Historical V5 ${d.holdoutsOpenedInThisPhase.historicalV5}, Synthetic V2 ${d.holdoutsOpenedInThisPhase.syntheticV2}.

## What the second stage HAS

### Fixtures
${d.frozenAndPresent.fixtures.count} fixtures, manifest \`${d.frozenAndPresent.fixtures.manifestHash}\`,
set version ${d.frozenAndPresent.fixtures.setVersion}, frozen at ${d.frozenAndPresent.fixtures.frozenAt}.

${d.frozenAndPresent.fixtures.note}

### Guardrail policy
${d.frozenAndPresent.guardrailPolicy.note}

Acceptance policy hash \`${d.frozenAndPresent.guardrailPolicy.acceptancePolicyHash}\`, minimum games per fixture ${d.frozenAndPresent.guardrailPolicy.minGamesPerHoldoutFixture}.

| guardrail | value |
| --- | --- |
${Object.entries(d.frozenAndPresent.guardrailPolicy.guardrails).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

### Seal
Registered ${yn(d.frozenAndPresent.seal.registered)} · access log \`${d.frozenAndPresent.seal.accessLogPath}\` ·
access count ${d.frozenAndPresent.seal.accessCount} · log on disk ${yn(d.frozenAndPresent.seal.accessLogExists)} · state ${d.frozenAndPresent.seal.state}

## What the second stage LACKS

${Object.entries(d.missing).map(([k, v]) => `### \`${k}\`\n\n${v}`).join("\n\n")}

## Why Historical V5 was not opened

${d.whyHistoricalV5WasNotOpened}

${d.irreversibility}

## Why nothing was authored here instead

${d.whyNotBuiltInThisPhase}

## What a preparation phase must produce

${d.requiredToUnblock.map((r, i) => `${i + 1}. ${r}`).join("\n")}

### Each has a worked precedent

${d.referenceImplementation.note}

| need | precedent |
| --- | --- |
${d.referenceImplementation.map.map((m) => `| ${m.need} | ${m.precedent} |`).join("\n")}

## What this blocker does not affect

${Object.entries(d.unaffected).map(([k, v]) => `- **${k}** — ${v}`).join("\n")}

Prepared commands executed: ${Object.entries(d.preparedCommandsExecuted).map(([k, v]) => `${k} ${v}`).join(" · ")}.

**Recommended next phase.** ${d.recommendedNextPhase}`);
  }

  if (has("phase6c4b2-final-summary")) {
    const A = R("phase6c4b2-final-summary"); const d = A.data;
    write("phase-6c4b2-limitations.md", `${prov(A)}# Phase 6C4B2 — limitations

**Outcome: \`${d.outcome}\`**

${d.finalVerdict}

## What this phase does NOT establish

${d.limitations.map((l) => `### \`${l.id}\`\n\n${l.detail}`).join("\n\n")}

## Claims explicitly not made

${d.claimsNotMade.map((c) => `- ${c}`).join("\n")}

## Artifacts deliberately not created

No holdout was opened, so none of the following exists — and their absence is
the honest record, not an omission:

${d.notCreatedBecauseNoHoldoutOpened.map((n) => `- \`${n}\``).join("\n")}

## Holdout state at the end of the phase

| set | state | access count | verdict |
| --- | --- | ---: | --- |
| \`historical-holdout-v3\` | ${d.priorHoldouts.historicalHoldoutV3.state} | ${d.priorHoldouts.historicalHoldoutV3.accessCount} | ${d.priorHoldouts.historicalHoldoutV3.verdict} |
| \`historical-holdout-v4\` | ${d.priorHoldouts.historicalHoldoutV4.state} | ${d.priorHoldouts.historicalHoldoutV4.accessCount} | ${d.priorHoldouts.historicalHoldoutV4.verdict} |
| \`historical-holdout-v5\` | ${d.historicalV5.state} | ${d.historicalV5.accessCount} | ${d.historicalV5.formalVerdict} |
| \`synthetic-stress-holdout-v2\` | ${d.syntheticV2.state} | ${d.syntheticV2.accessCount} | ${d.syntheticV2.formalVerdict} |

## Candidate 1 status, unchanged

\`${d.candidate.candidateId}\` · ${d.candidate.calibrationStatus} · formal validation ${d.candidate.formalValidationStatus} ·
calibration ${d.candidate.possessionCalibrationVersion} · core \`${d.candidate.coreHash.slice(0, 16)}...\`

## Production isolation

engine ${d.productionIsolation.engineVersion} · app ${d.productionIsolation.appVersion} ·
main \`${d.productionIsolation.main}\` · preview deployed ${yn(d.productionIsolation.previewDeployed)} ·
production deployed ${yn(d.productionIsolation.productionDeployed)}

**Recommended next phase.** ${d.recommendedNextPhase}`);
  }

  console.log(written.length ? written.join("\n") : "no 6c4b2 artifacts yet");
}
