// ── Public Competitive Profiles V1 — the contract (Phase 9F) ──────────────────
// A public profile answers WHO IS THIS ERACLASH PLAYER? It never answers WHAT
// PERSONAL INFORMATION DO WE KNOW ABOUT THIS ACCOUNT?
//
// An EraClash account is private by default. Creating one does not create a
// publicly discoverable profile, and appearing on the Phase 9E leaderboard does
// not grant anyone access to anything else. Public exposure is explicit,
// minimal, reversible, safe and decided by the server.
//
// PUBLIC_PROFILE_POWER_EFFECT = 0. Nothing here touches a roll, a draft, an
// era, a coach, a Legend Rival, a Challenge, a Competitive Rating outcome or an
// XP award. 9F CONSUMES rating and progression state for display; it computes
// no competitive outcome of its own.
//
// This module is pure: no fetch, no DOM, no database. The server library, the
// SQL and the components are all pinned against it by the gates.

// ── versions and the power invariant ─────────────────────────────────────────
export const PUBLIC_PROFILE_VERSION = "1.0.0";
/** Zero, forever. A public profile is identity; identity is not basketball power. */
export const PUBLIC_PROFILE_POWER_EFFECT = 0;

// ── the preference ───────────────────────────────────────────────────────────
// Deliberately SEPARATE from Phase 9E's leaderboard_visibility. The two are
// never combined: a player may want a ranking without a clickable profile, or a
// shareable profile without being in the global listing. All four combinations
// are legitimate and each is preserved exactly as chosen.
export const PROFILE_VISIBILITY_PREF_KEY = "profile_visibility";
export const PROFILE_VISIBILITY = Object.freeze(["private", "public"]);
export const PROFILE_VISIBILITY_DEFAULT = "private";
export const LEADERBOARD_VISIBILITY_PREF_KEY = "leaderboard_visibility";
/** The independence, written down so a gate can assert it. */
export const VISIBILITY_INDEPENDENCE = Object.freeze({
  profile_visibility: "governs access to the richer Phase 9F public competitive profile",
  leaderboard_visibility: "governs inclusion in the Phase 9E public Competitive Rating leaderboard",
  combined: false,
  combinations: Object.freeze([
    Object.freeze({ profile: "private", leaderboard: "private", profileReachable: false, onLeaderboard: false, rowLinksToProfile: false }),
    Object.freeze({ profile: "private", leaderboard: "public", profileReachable: false, onLeaderboard: true, rowLinksToProfile: false }),
    Object.freeze({ profile: "public", leaderboard: "private", profileReachable: true, onLeaderboard: false, rowLinksToProfile: false }),
    Object.freeze({ profile: "public", leaderboard: "public", profileReachable: true, onLeaderboard: true, rowLinksToProfile: true }),
  ]),
});
export const isPublicProfileVisibility = (v) => v === "public";
/** The stored preference, defaulted. Anything unrecognised reads as private. */
export const profileVisibilityFrom = (prefs) =>
  PROFILE_VISIBILITY.includes(prefs?.[PROFILE_VISIBILITY_PREF_KEY]) ? prefs[PROFILE_VISIBILITY_PREF_KEY] : PROFILE_VISIBILITY_DEFAULT;

// ── the safe public identifier ───────────────────────────────────────────────
// An opaque slug, generated by the database. Not the auth id, not the database
// id, not derived from an email, not sequential, and not guessable: 20 symbols
// drawn uniformly from a 32-symbol alphabet is 100 bits. Crockford's base32
// alphabet without i, l, o and u, so a slug read aloud or retyped is unambiguous.
export const SLUG_ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz";
export const SLUG_LENGTH = 20;
export const SLUG_ENTROPY_BITS = 100;
export const SLUG_PATTERN = /^[0-9abcdefghjkmnpqrstvwxyz]{20}$/;
export const isSlug = (s) => typeof s === "string" && SLUG_PATTERN.test(s);
/** A uuid must never be accepted where a slug belongs — that is the enumeration door. */
export const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const looksLikeUuid = (s) => typeof s === "string" && UUID_PATTERN.test(s);
export const SLUG_RULES = Object.freeze({
  stableAcrossDisplayNameChanges: true,
  derivedFromEmail: false,
  isAuthId: false,
  isDatabaseId: false,
  sequentiallyEnumerable: false,
  serverGenerated: true,
  survivesProfileEdits: true,
  invalidatedOnAccountDeletion: true,
});

// ── the route ────────────────────────────────────────────────────────────────
export const PUBLIC_PROFILE_ROUTE = "/player";
export const profilePath = (slug) => (isSlug(slug) ? `${PUBLIC_PROFILE_ROUTE}/${slug}` : null);
export const profileUrl = (origin, slug) => (isSlug(slug) && origin ? `${String(origin).replace(/\/$/, "")}${profilePath(slug)}` : null);
/** The slug in /player/<slug>, or null. Anything else — including a uuid — is not a slug. */
export const slugFromPath = (path) => {
  const m = String(path || "").match(/^\/player\/([^/?#]+)/);
  return m && isSlug(m[1]) ? m[1] : null;
};

// ── the safe public projection ───────────────────────────────────────────────
// The server decides these fields; the browser only renders them. A field is
// absent from a public profile unless it appears here, and no field is added
// merely because the database happens to hold it.
export const PUBLIC_PROFILE_FIELDS = Object.freeze([
  "slug", "displayName", "initials", "state",
  "rating", "rank", "wins", "losses", "ties", "matches", "winPct",
  "level", "featured", "placement", "profileVersion",
]);
/** A provisional public profile carries no rating and no rank — Phase 9E kept both private until placement. */
export const PUBLIC_PROFILE_FIELDS_PROVISIONAL = Object.freeze([
  "slug", "displayName", "initials", "state", "level", "featured", "placement", "profileVersion",
]);
export const FORBIDDEN_PROFILE_FIELDS = Object.freeze([
  "email", "user_id", "userId", "authId", "auth_id", "provider", "phone", "location",
  "created_at", "createdAt", "joined", "joinedAt", "birth", "ip", "session", "sessionId",
  "cookie", "token", "accessToken", "refresh", "rosters", "savedRosters", "favorites",
  "xp", "totalXp", "xp_ledger", "xpLedger", "xpEvents", "challenge_id", "challengeId",
  "attempt_id", "attemptId", "challengeCode", "seed", "seed_id", "result_id",
  "supabase", "moderation", "prefs", "preferences", "displayNameHistory", "deletedNames",
]);

// ── profile state ────────────────────────────────────────────────────────────
// Mirrors Phase 9E's own vocabulary so the two surfaces cannot drift apart.
export const PROFILE_STATES = Object.freeze(["placed", "provisional", "none"]);
export const PROFILE_STATE_COPY = Object.freeze({
  placed: "COMPETITIVE",
  provisional: "PROVISIONAL",
  none: "NO RATED CHALLENGES YET",
});
export const profileState = ({ placed = false, matches = 0 } = {}) => (placed ? "placed" : matches > 0 ? "provisional" : "none");
/**
 * A public rank is shown only when the account is genuinely eligible for one —
 * PLACED and on the public leaderboard. This is the documented rule, and the
 * SQL projection implements it (the gates pin the two together).
 *
 * It is deliberately NOT applied inside publicProfile(): leaderboard_visibility
 * is a private preference and must never travel in a public payload, so a public
 * row cannot carry it and the projection has no business re-deriving the rule
 * from it. The database is the authority; a public row simply carries the rank
 * it was granted, or none.
 */
export const showsPublicRank = ({ state, leaderboardVisibility } = {}) => state === "placed" && leaderboardVisibility === "public";
/** A public profile shows a rating only once placed. Never an estimate, never a "would be #X". */
export const showsPublicRating = ({ state } = {}) => state === "placed";

// ── featured achievements ────────────────────────────────────────────────────
export const MAX_FEATURED_ACHIEVEMENTS = 3;
export const FEATURED_REJECTIONS = Object.freeze({
  NOT_UNLOCKED: "not_unlocked",
  UNKNOWN: "unknown_achievement",
  DUPLICATE: "duplicate",
  TOO_MANY: "too_many",
  MALFORMED: "malformed",
});
/**
 * The one place the featured list is validated. `unlocked` is the account's own
 * unlocked ids and `known` the catalog's ids — both supplied by the server, so a
 * browser cannot widen either. Returns the accepted list and why anything fell out.
 * Order is the caller's; an empty list is valid and clears the showcase.
 */
export const validateFeatured = (ids, { unlocked = [], known = [] } = {}) => {
  if (!Array.isArray(ids)) return { ok: false, reason: FEATURED_REJECTIONS.MALFORMED, featured: [], rejected: [] };
  if (ids.some((id) => typeof id !== "string" || !id)) return { ok: false, reason: FEATURED_REJECTIONS.MALFORMED, featured: [], rejected: [] };
  if (ids.length > MAX_FEATURED_ACHIEVEMENTS) return { ok: false, reason: FEATURED_REJECTIONS.TOO_MANY, featured: [], rejected: ids.slice(MAX_FEATURED_ACHIEVEMENTS) };
  const unlockedSet = new Set(unlocked), knownSet = new Set(known), seen = new Set();
  const featured = [], rejected = [];
  for (const id of ids) {
    if (seen.has(id)) { rejected.push({ id, reason: FEATURED_REJECTIONS.DUPLICATE }); continue; }
    seen.add(id);
    if (!knownSet.has(id)) { rejected.push({ id, reason: FEATURED_REJECTIONS.UNKNOWN }); continue; }
    if (!unlockedSet.has(id)) { rejected.push({ id, reason: FEATURED_REJECTIONS.NOT_UNLOCKED }); continue; }
    featured.push(id);
  }
  return { ok: rejected.length === 0, reason: rejected[0]?.reason ?? null, featured, rejected };
};

// ── the public projection ────────────────────────────────────────────────────
/**
 * The only shape a public profile may take. Everything is derived from rows the
 * server already trusts; nothing is copied from a request. A provisional or
 * unrated account loses its rating and rank here, not in the component.
 */
export const publicProfile = (row = {}) => {
  const state = profileState({ placed: !!row.placed, matches: Number(row.rated_matches ?? row.matches ?? 0) });
  const matches = Number(row.rated_matches ?? row.matches ?? 0);
  const wins = Number(row.rated_wins ?? row.wins ?? 0), losses = Number(row.rated_losses ?? row.losses ?? 0), ties = Number(row.rated_ties ?? row.ties ?? 0);
  const base = {
    slug: row.slug ?? null,
    displayName: row.display_name ?? row.displayName ?? "Coach",
    initials: initialsOf(row.display_name ?? row.displayName ?? "Coach"),
    state,
    level: row.career_level ?? row.level ?? null,
    featured: Array.isArray(row.featured) ? row.featured.slice(0, MAX_FEATURED_ACHIEVEMENTS) : [],
    placement: { matches, matchesTarget: 5, opponents: Number(row.unique_opponents ?? row.opponents ?? 0), opponentsTarget: 3 },
    profileVersion: PUBLIC_PROFILE_VERSION,
  };
  if (!showsPublicRating({ state })) return base;
  return {
    ...base,
    rating: Number(row.current_rating ?? row.rating ?? 0),
    // the authority already applied showsPublicRank; a withheld rank arrives null
    rank: row.rank ?? null,
    wins, losses, ties, matches,
    winPct: matches > 0 ? Math.round((wins / matches) * 100) : null,
  };
};

/** Two letters at most, from the display name. Never an id, never an email local part. */
export const initialsOf = (name) => String(name || "Coach").trim().split(/\s+/).slice(0, 2).map((w) => w[0] || "").join("").toUpperCase() || "C";
export const fmt = (n) => (typeof n === "number" && Number.isFinite(n) ? n.toLocaleString("en-US") : "—");

// ── what a screen reader is told ─────────────────────────────────────────────
export const announceProfile = (p) => {
  if (!p) return "";
  const name = p.displayName;
  if (p.state !== "placed") {
    if (p.state === "none") return `${name}. No rated Challenges yet.`;
    return `${name}. Competitive status provisional. ${p.placement.matches} of ${p.placement.matchesTarget} rated matches and ${p.placement.opponents} of ${p.placement.opponentsTarget} unique opponents completed.`;
  }
  const parts = [`${name}.`, `Competitive Rating ${fmt(p.rating)}.`];
  if (p.rank) parts.push(`Global rank ${p.rank}.`);
  parts.push(`Record ${p.wins} ${p.wins === 1 ? "win" : "wins"}, ${p.losses} ${p.losses === 1 ? "loss" : "losses"}, ${p.ties} ${p.ties === 1 ? "tie" : "ties"}.`);
  if (p.level != null) parts.push(`Career Level ${p.level}.`);
  return parts.join(" ");
};
export const announceFeatured = (names = []) =>
  names.length ? `Featured achievements: ${names.join(", ")}.` : "No featured achievements.";

// ── telemetry ────────────────────────────────────────────────────────────────
// A closed vocabulary, mirrored by api/events.js and src/activation.js. Metadata
// carries categories and counts only — never a name, an id, a slug or a token.
export const PROFILE_EVENTS = Object.freeze({
  PUBLIC_VIEWED: "public_profile_viewed",
  VISIBILITY_CHANGED: "profile_visibility_changed",
  PREVIEWED: "public_profile_previewed",
  SHARED: "public_profile_shared",
  FEATURED_UPDATED: "featured_achievement_updated",
  LEADERBOARD_OPENED: "leaderboard_profile_opened",
});
export const PROFILE_EVENT_METADATA_ALLOWED = Object.freeze([
  "authState", "visibility", "state", "featuredCount", "hasRank", "shareMethod", "success", "failureCode", "reason", "viewer",
]);
export const PROFILE_EVENT_METADATA_FORBIDDEN = Object.freeze([
  "displayName", "email", "accountId", "userId", "authId", "slug", "challengeId", "attemptId", "challengeCode", "token", "sessionId",
]);

// ── the policy, for the record ───────────────────────────────────────────────
export const PUBLIC_PROFILE_POLICY = Object.freeze({
  version: PUBLIC_PROFILE_VERSION,
  powerEffect: PUBLIC_PROFILE_POWER_EFFECT,
  default: "private — creating an account creates no publicly discoverable profile",
  identifier: `opaque server-generated slug, ${SLUG_LENGTH} symbols of a ${SLUG_ALPHABET.length}-symbol alphabet (${SLUG_ENTROPY_BITS} bits)`,
  route: `${PUBLIC_PROFILE_ROUTE}/<slug>`,
  enumeration: "no listing endpoint of any kind; a profile is reachable only by its slug. The Phase 9E leaderboard remains the one bounded public competitive listing.",
  provisional: "no rating, no rank, no estimate — only the placement progress, preserving the Phase 9E invariant",
  rank: "shown only when the account is placed AND leaderboard_visibility is public",
  featured: `up to ${MAX_FEATURED_ACHIEVEMENTS} already-unlocked achievements, ownership validated server-side`,
  consumes: ["Competitive Rating (Phase 9E)", "Career Level and achievement unlocks (Phase 9D)"],
  computes: "nothing competitive — no rating, no XP, no unlock, no outcome",
  notBuilt: Object.freeze([
    "friends", "following", "followers", "direct messages", "chat", "comments", "likes",
    "feeds", "activity feeds", "profile search", "player directory", "global user search",
    "presence indicators", "contact discovery", "email discovery", "seasons", "tournaments",
    "clans", "leagues", "teams or guilds", "trading", "paid profile boosts",
    "gameplay rewards", "rating boosts", "XP boosts", "XP leaderboard",
  ]),
});
