#!/usr/bin/env node
// ── Render Phase 6C4B1 documents from artifacts ─────────────────────────────
//   npm run v5:report
// Formats only. Never sums, counts, averages or derives — every number below
// is read from the artifact that produced it.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt } from "../../src/v3/calibration/artifacts.js";
import { DIR } from "./preflight6c4b1.mjs";

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const has = (n) => artifactExists(n, DIR);
const R = (n) => readArtifact(n, DIR);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run v5:report  from: ${a.generationCommand} -->\n`;
const yn = (b) => (b ? "**yes**" : "**no**");

if (import.meta.url === `file://${process.argv[1]}`) {
  if (has("candidate-core-graph-certification")) {
    const A = R("candidate-core-graph-certification"); const d = A.data;
    write("candidate1-core-certification.md", `${prov(A)}# Candidate 1 — core graph certification

Discovery is parser-backed (\`${d.parser}\`), version ${d.candidateCoreGraphVersion}, and cross-checked
against what Candidate 1 actually executes.

| fact | value |
| --- | ---: |
| entry points | ${d.entryPoints.length} |
| declared modules | ${d.declaredModuleCount} |
| modules observed executing | ${d.runtimeObservedCount} |
| simulation paths exercised | ${d.simulationPathsExercised.length} |
| executed but undeclared | **${d.missingExecutedModules.length}** |
| unresolved dynamic imports | ${d.unresolvedDynamicImports.length} |
| unresolvable relative specifiers | ${d.unresolvableRelativeSpecifiers.length} |
| current core hash | \`${d.currentCoreHash}\` |
| Candidate 1 locked core hash | \`${d.candidate1LockedCoreHash}\` |

\`src/v3/actions/offensivePlan.js\` declared: ${yn(d.declaredModules.includes("src/v3/actions/offensivePlan.js"))} · observed executing: ${yn(d.runtimeObservedModules.includes("src/v3/actions/offensivePlan.js"))}

## The historical defect

- **v1** — ${d.historicalDefect.v1}
- **v2** — ${d.historicalDefect.v2}
- **v3** — ${d.historicalDefect.v3}

## Continuity

The parser reproduces the prior builder's hash on this tree
(${yn(d.priorBuilderComparison.identical)}, ${d.priorBuilderComparison.priorBuilderFileCount} files both ways), so replacing the
builder introduces no discontinuity of its own.

## Difference from the lock

${d.changedSinceLock.length === 0 ? "No core file differs from the lock." : `${d.changedSinceLock.length} file(s) differ:

| file | locked sha256 | current sha256 |
| --- | --- | --- |
${d.changedSinceLock.map((c) => `| \`${c.path}\` | \`${c.lockedSha256.slice(0, 16)}...\` | \`${c.currentSha256.slice(0, 16)}...\` |`).join("\n")}

Substituting the locked contents back reproduces \`${d.lockReproducedFromCurrentGraph.slice(0, 16)}...\`, the recorded lock hash.`}

## Simulation paths exercised

${d.simulationPathsExercised.map((p) => `- ${p}`).join("\n")}`);
  }

  if (has("candidate-identity-separation")) {
    const A = R("candidate-identity-separation"); const d = A.data;
    const rep = has("candidate1-identity-repair") ? R("candidate1-identity-repair").data : null;
    write("candidate1-identity-separation.md", `${prov(A)}# Candidate 0 / Candidate 1 identity separation

Both candidates carry the same parameter-set hash by design — no parameter was
ever fitted — so identity must come from somewhere else.

| | Candidate 0 | Candidate 1 |
| --- | --- | --- |
| candidate id | \`${d.candidate0.candidateId}\` | \`${d.candidate1.candidateId}\` |
| core hash | \`${d.candidate0.coreHash.slice(0, 16)}...\` | \`${d.candidate1.coreHash.slice(0, 16)}...\` |
| parameter-set hash | \`${d.candidate0.parameterSetHash.slice(0, 16)}...\` | \`${d.candidate1.parameterSetHash.slice(0, 16)}...\` |
| possessionCalibrationVersion | ${d.candidate0.possessionCalibrationVersion} | ${d.candidate1.possessionCalibrationVersion} |

Candidate 0 was measured by running its real code: ${d.candidate0.note}.

**Surfaces compared:** ${d.surfacesCompared.map((s) => `\`${s}\``).join(", ")}
**Comparisons:** ${d.comparisons} · **Collisions:** ${d.collisions}

| probe case | colliding surfaces | behaviour differs | C0 score | C1 score |
| --- | ---: | --- | --- | --- |
${d.rows.map((r) => `| ${r.case} | ${r.collidingSurfaces.length} | ${yn(r.behaviourDiffers)} | ${JSON.stringify(r.candidate0Score)} | ${JSON.stringify(r.candidate1Score)} |`).join("\n")}
${rep ? `
## The defect that made this necessary

${rep.defect.mechanism}

${rep.defect.collisionsObserved} of ${rep.defect.probeCases} probe cases collided outright. ${rep.defect.severity}

| case | C0 fingerprint | C1 fingerprint | collided | behaviour differed |
| --- | --- | --- | --- | --- |
${rep.defect.evidence.map((e) => `| ${e.case} | \`${e.candidate0Fingerprint.slice(0, 12)}\` | \`${e.candidate1Fingerprint.slice(0, 12)}\` | ${yn(e.collided)} | ${yn(e.behaviourDiffered)} |`).join("\n")}

## The repair, and its proof

${rep.repair.change}

${rep.repair.productionUntouched}

**Behaviour proof:** ${rep.behaviourProof.cases} cases, hash \`${rep.behaviourProof.behaviourHashBefore.slice(0, 16)}...\` before and after,
${rep.behaviourProof.changedCases.length} changed. Coverage: ${rep.behaviourProof.coverage}.` : ""}

## Module-version staleness

${d.moduleVersionStaleness.finding}

Why not repaired here: ${d.moduleVersionStaleness.whyNotRepairedHere}
Mitigation: ${d.moduleVersionStaleness.mitigated}
Recommendation: ${d.moduleVersionStaleness.recommendation}`);
  }

  if (has("realized-zone-measurement-certification")) {
    const A = R("realized-zone-measurement-certification"); const d = A.data;
    write("realized-zone-measurement-certification.md", `${prov(A)}# Realized zone measurement — certification

Version ${d.realizedZoneMeasurementVersion}. Four states, never collapsed:

${Object.entries(d.states).map(([k, v]) => `- **${k}** — ${v}`).join("\n")}

## The prior defect

${d.priorDefect.v1}

Symptom: ${d.priorDefect.symptom}
Repaired in: ${d.priorDefect.repairedIn}

## Controls (${d.gamesPerCell} games per cell)

| control | possessions | permitted games | realized zone possessions | realized share | zone attacks | man possessions |
| --- | ---: | ---: | ---: | ---: | ---: | ---: |
${Object.values(d.cells).map((c) => `| ${c.label} | ${c.possessions} | ${c.planPermittedGames}/${c.games} | ${c.shellSelectedPossessions} | ${c.realizedZoneShare} | ${c.zoneAttackPossessions} | ${c.manPossessions} |`).join("\n")}

**Certification: ${d.pass ? "PASS" : "FAIL"}**${d.failedGates.length ? ` (failed: ${d.failedGates.join(", ")})` : ""}

${d.candidateBehaviourUnchanged}`);
  }

  if (has("era-reference-certification-candidate1")) {
    const A = R("era-reference-certification-candidate1"); const d = A.data;
    write("era-reference-certification-candidate1.md", `${prov(A)}# Era Style references — re-certified under Candidate 1

Version ${d.eraReferenceCertificationVersion}. ${d.gamesPerEra} paired games per era at core
\`${d.certifiedUnder.coreHash.slice(0, 16)}...\`, calibration ${d.certifiedUnder.possessionCalibrationVersion}.

**${d.referencesCertified}/8 certified · ${d.failedReferences} failed · ${d.referencesReplaced} replaced · V5-pool overlap ${d.v5PoolOverlap}**

The prior certification (${d.priorCertification.version}, under ${d.priorCertification.certifiedUnder}) is read
exactly as frozen and is not modified.

| era | ppp | pace | gold rate | 95% CI | realized zone | vs population | discrimination | certified |
| --- | ---: | ---: | ---: | --- | ---: | ---: | ---: | --- |
${d.references.map((r) => `| ${r.era} | ${r.candidate1SelfBaselines.pppVsReference.mean} | ${r.candidate1SelfBaselines.gamePace.mean} | ${r.sideSymmetry.goldWinRate} | [${r.sideSymmetry.ci95.lower}, ${r.sideSymmetry.ci95.upper}] | ${r.realizedZoneShare} | ${r.meanReferenceOutscores >= 0 ? "+" : ""}${r.meanReferenceOutscores} | ${r.discriminationSpread} | ${yn(r.certifiedUnderCandidate1)} |`).join("\n")}

| gate | result |
| --- | --- |
| eight eras certified | ${yn(d.referencesCertified === 8)} |
| side-symmetry failures | ${d.sideSymmetryFailures} |
| invariant failures | ${d.invariantFailures} |
| replay failures | ${d.replayFailures} |
| V5-pool overlap | ${d.v5PoolOverlap} |

## A criterion withdrawn

**${d.withdrawnCriterion.criterion}**

${d.withdrawnCriterion.why}

It would have failed: ${d.withdrawnCriterion.erasItWouldHaveFailed.join(", ")}.

## Population standing

Phase 6C4A attributed part of three residual failures to these references being
champions-median fives. Measured, each reference plays its era's calibration
teams; a positive figure means the reference outscores them.

${d.references.map((r) => `**${r.era}** (mean ${r.meanReferenceOutscores >= 0 ? "+" : ""}${r.meanReferenceOutscores}): ${r.populationStanding.map((p) => `${p.fixtureId} ${p.referenceOutscores >= 0 ? "+" : ""}${p.referenceOutscores}`).join(" · ")}`).join("\n\n")}`);
  }

  if (has("historical-observability-certification-candidate1")) {
    const A = R("historical-observability-certification-candidate1"); const d = A.data;
    const res = has("candidate1-residual-dispositions") ? R("candidate1-residual-dispositions").data : null;
    write("historical-observability-certification-candidate1.md", `${prov(A)}# Historical trait observability — re-certified under Candidate 1

Version ${d.historicalObservabilityCertificationVersion}. ${d.gamesPerCell} games per control cell.

**${d.metricsCertified}/${d.metricsTotal} metrics certified · ${d.eligibleTraitCount} traits eligible to score**

| observability class | traits |
| --- | ---: |
${Object.entries(d.observabilityClassCounts).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

Eligible by class: ${Object.entries(d.eligibleByClass).map(([k, v]) => `${k} ${v}`).join(" · ")}

## Metrics

| metric | strong | neutral | weak | control range | practical margin | certified | under Candidate 0 |
| --- | ---: | ---: | ---: | ---: | ---: | --- | --- |
${d.results.map((r) => `| \`${r.metric}\` | ${fmt(r.cells.strong.mean)} | ${fmt(r.cells.neutral.mean)} | ${fmt(r.cells.weak.mean)} | ${r.controlRange ?? "—"} | ${r.practicalMargin ?? "—"} | ${yn(r.certified)} | ${r.certifiedUnderCandidate0 == null ? "—" : yn(r.certifiedUnderCandidate0)} |`).join("\n")}

### What Candidate 1 changed

${d.metricsChangedFromCandidate0.map((m) => `- \`${m.metric}\`: ${m.candidate0 ? "certified" : "failed"} under Candidate 0 → ${m.candidate1 ? "**certified**" : "**failed**"} under Candidate 1`).join("\n")}

### Practical separation

A metric whose strongest-to-weakest control range is smaller than its own
practical margin cannot produce a practically material finding, so it cannot
support a verdict.

| metric | control range | practical margin |
| --- | ---: | ---: |
${d.practicalSeparationFailures.map((f) => `| \`${f.metric}\` | ${f.controlRange} | ${f.practicalMargin} |`).join("\n")}

## Dependency guards

- mirror PPP separated: ${yn(d.dependencyGraph.mirrorSeparated)} — ${d.dependencyGraph.mirrorSurfaces.map((m) => `\`${m.metric}\` on ${m.identifiableOn.join("/")}`).join("; ")}
- registry surface problems: ${d.dependencyGraph.registrySurfaceProblems.length}
- per-fixture contradiction detector rejects a mirror rubric: ${yn(d.dependencyGraph.perFixtureDetector.rejectsMirrorRubric)}
- contradictory dependent rules: ${d.contradictoryDependentRules}
${res ? `
## Candidate 1 residual dispositions

**${res.candidate1Verdict}** · unresolved substantive residuals: ${res.unresolvedSubstantiveCandidate1Residuals}

${res.residuals.map((r) => `### \`${r.residualId}\` → \`${r.disposition}\`

Prior attribution: ${r.priorAttribution}

${r.reasoning}

V5 consequence: ${r.v5Consequence}`).join("\n\n")}

### The reference attribution, revised

${res.referenceAttributionRevised.claim}

${res.referenceAttributionRevised.finding}` : ""}`);
  }

  if (has("trait-practical-margin-policy-v5")) {
    const A = R("trait-practical-margin-policy-v5"); const d = A.data;
    write("historical-v5-practical-margin-policy.md", `${prov(A)}# Historical V5 practical-margin policy

**Frozen. policyHash \`${d.policyHash}\`. Version ${d.historicalTraitPracticalMarginPolicyVersion}.**

Applies from ${d.appliesFrom}. ${d.neverAppliesTo}.

Supersedes ${d.supersedes.version} (\`${d.supersedes.policyHash.slice(0, 16)}...\`): ${d.supersedes.whatChanged}

## The dual gate

- **hard fail** — ${d.rule.hardFail}
- **directional soft fail** — ${d.rule.directionalSoftFail}
- **pass** — ${d.rule.pass}

${d.rule.dualGate}

Reporting states: ${d.rule.reportingStates.map((x) => `\`${x}\``).join(", ")}

## Margins

| metric | margin | unit | family | binding | 8xSE at n=${d.rule.protocolGamesPerSurface ?? 4096} | certified |
| --- | ---: | --- | --- | --- | ---: | --- |
${Object.entries(d.metrics).map(([m, v]) => `| \`${m}\` | ${v.margin} | ${v.unit} | ${v.traitFamily} | ${v.binding} | ${v.noiseEstimate.noiseComponent ?? "n/a"} | ${yn(v.metricCertifiedUnderCandidate1)} |`).join("\n")}

### Rationales

${Object.entries(d.metrics).map(([m, v]) => `- \`${m}\` — ${v.practicalRationale}`).join("\n")}

Noise basis: ${d.noiseBasis}`);
  }

  if (has("historical-v5-candidate-pool-v2")) {
    const A = R("historical-v5-candidate-pool-v2"); const d = A.data;
    write("historical-v5-candidate-pool-v2.md", `${prov(A)}# Historical V5 candidate pool, version ${d.historicalV5CandidatePoolVersion}

**${d.eligibleTeamCount} eligible team-seasons · ${d.eligiblePairCount} eligible pairs · minimum met ${yn(d.meetsMinimum)}**
poolHash \`${d.poolHash}\`

${d.selectionBasis}

**Candidate 1 simulations used: ${d.candidate1SimulationsUsed}.**

Supersedes ${d.supersedes.version} (\`${d.supersedes.poolHash.slice(0, 16)}...\`): ${d.supersedes.note}.

| era | eligible teams | eligible pairs | cross-franchise pairs |
| --- | ---: | ---: | ---: |
${Object.keys(d.eligiblePairsByEra).map((e) => `| ${e} | ${d.eligibleByEra[e]} | ${d.eligiblePairsByEra[e]} | ${d.crossFranchisePairsByEra[e]} |`).join("\n")}

Eras with 2+ eligible pairs: **${d.erasWithAtLeastTwoEligiblePairs}/8** · with 3+: **${d.erasWithAtLeastThreeEligiblePairs}/8**

## Instruments read

- observability certification \`${d.instrumentsRead.observabilityCertification.slice(0, 16)}...\` (${d.instrumentsRead.eligibleTraitCount} eligible traits)
- era-reference certification \`${d.instrumentsRead.eraReferenceCertification.slice(0, 16)}...\` (${d.instrumentsRead.certifiedEras.length} certified eras)

## Exclusions, all enforced in code

| exclusion set | members |
| --- | ---: |
${Object.entries(d.exclusions).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

Seen team-seasons blocked: ${d.seenTeamSeasons} · seen fives blocked: ${d.seenFivesBlocked} · era-reference fives blocked: ${d.eraReferenceFivesBlocked}

## Pool

| fixture | era | team-season | coach | source | observable traits | eligible |
| --- | --- | --- | --- | --- | ---: | --- |
${d.teams.map((t) => `| \`${t.fixtureId}\` | ${t.eraStyleId} | ${t.teamName} ${t.season} | \`${t.coachId}\` | ${t.source === "NEW_IN_V5" ? "new" : "carried"} | ${t.observableTraitCount} | ${t.eligible ? "yes" : `no — ${t.ineligibleReasons.join(", ")}`} |`).join("\n")}`);
  }

  if (has("historical-v5-selection")) {
    const A = R("historical-v5-selection"); const d = A.data;
    const P = R("historical-v5-selection-policy").data;
    write("historical-v5-selection.md", `${prov(A)}# Historical Holdout V5 — selection

**${d.matchups.length} matchups · ${d.distinctTeams} distinct team-seasons · ${d.eraStylesRepresented.length} era styles**
selectionHash \`${d.selectionHash}\` under policy \`${d.selectionPolicyHash.slice(0, 16)}...\` (version ${d.historicalV5SelectionVersion})

**Candidate 1 outputs consulted: ${d.candidate1OutputsConsulted}.**

## The eight matchups

| era | matchup | pair type | score | observable traits | dimensions added |
| --- | --- | --- | ---: | ---: | --- |
${d.matchups.map((m) => `| ${m.era} | ${m.teamAName} vs ${m.teamBName} | ${m.pairType} | ${m.score.total} | ${m.observableTraits.union.length} | ${m.newDimensionsContributed.join(", ") || "—"} |`).join("\n")}

### Why each won

${d.matchups.map((m) => `- **${m.era}** — ${m.wonBecause}`).join("\n")}

## Diversity

Covered ${d.diversityDimensionsCovered.length} of ${d.diversityDimensionsAvailable.length} dimensions: ${d.diversityDimensionsCovered.join(", ")}

Pair types: ${Object.entries(d.pairTypes).map(([k, v]) => `${k} ${v}`).join(", ")}

## Determinism

| property | result |
| --- | --- |
| identical on repeat | ${yn(d.determinism.repeatIdentical)} |
| identical with the pair list reversed | ${yn(d.determinism.reversedIdentical)} |
| identical with the pair list rotated | ${yn(d.determinism.rotatedIdentical)} |
${d.supersededSelection ? `| reproduced the invalidated selection ${d.supersededSelection.version} exactly | ${yn(d.supersededSelection.reproducedIdentically)} |

**Why a selection was invalidated.** ${d.supersededSelection.whyInvalidated}` : ""}

## Permitted and forbidden inputs

Permitted: ${P.permittedInputs.join(", ")}.
Forbidden: ${P.forbiddenInputs.join(", ")}.

## Rejected alternatives (${d.rejectedAlternatives.length})

| era | pair | score | reason |
| --- | --- | ---: | --- |
${d.rejectedAlternatives.slice(0, 20).map((r) => `| ${r.era} | ${r.pairId} | ${r.total} | ${r.reason} |`).join("\n")}
${d.rejectedAlternatives.length > 20 ? `\n…and ${d.rejectedAlternatives.length - 20} more in the artifact.` : ""}`);
  }

  if (has("historical-holdout-v5-manifest")) {
    const A = R("historical-holdout-v5-manifest"); const d = A.data;
    write("historical-v5-manifest.md", `${prov(A)}# Historical Holdout V5 — manifest

Version ${d.historicalHoldoutManifestVersion} · holdout set version ${d.holdoutVersion} · manifestHash \`${d.manifestHash}\`

| fact | value |
| --- | ---: |
| matchups | ${d.matchupCount} |
| team-seasons | ${d.teamCount} |
| player profiles | ${d.playerProfileCount} |
| coaches | ${d.coachCount} |
| scored traits | ${d.scoredTraitCount} |
| excluded traits | ${d.excludedTraitCount} |
| usable team targets | ${d.targetFreeze.usableTeamTargets} |
| null targets | ${d.targetFreeze.nullTargets} |

${d.targetFreeze.note}

## Bound hashes

${Object.entries(d.hashes).map(([k, v]) => `- \`${k}\` — \`${v}\``).join("\n")}

## Matchups

${d.matchups.map((m) => `### ${m.matchupId} — ${m.eraStyleId}

**${m.teamA.teamName} ${m.teamA.season}** (\`${m.teamA.coachId}\`) vs **${m.teamB.teamName} ${m.teamB.season}** (\`${m.teamB.coachId}\`)

Surfaces: ${m.surfaces.join(", ")} · era reference \`${m.eraReference.referenceHash.slice(0, 16)}...\`

| side | scored traits | excluded |
| --- | --- | --- |
| A | ${m.teamA.scoredTraits.map((t) => `\`${t.traitId}\``).join(", ")} | ${m.teamA.excludedTraits.map((t) => `\`${t.traitId}\``).join(", ") || "—"} |
| B | ${m.teamB.scoredTraits.map((t) => `\`${t.traitId}\``).join(", ")} | ${m.teamB.excludedTraits.map((t) => `\`${t.traitId}\``).join(", ") || "—"} |`).join("\n\n")}

${d.immutability}`);
  }

  if (has("historical-holdout-v5-seeds")) {
    const A = R("historical-holdout-v5-seeds"); const d = A.data;
    write("historical-v5-seeds.md", `${prov(A)}# Historical Holdout V5 — seed freeze

Version ${d.historicalHoldoutSeedSetVersion} · seedHash \`${d.seedHash}\`
master commitment \`${d.masterCommitment}\`

| volume | value |
| --- | ---: |
| matchups | ${d.volume.matchups} |
| surfaces per matchup | ${d.volume.surfacesPerMatchup} |
| pairs per surface | ${d.volume.pairsPerSurface} |
| games per surface | ${d.volume.gamesPerSurface} |
| total games | ${d.volume.totalGames} |
| holdout seeds | ${d.volume.holdoutSeedCount} |

Generation: ${d.generationAlgorithm}
Addressing: \`${d.surfaceAddressing}\`

## Streams

${Object.entries(d.streams).map(([k, v]) => `- \`${k}\` — ${v.purpose} (commitment \`${v.streamCommitment}\`)`).join("\n")}

## Disjointness proof

**${d.disjointnessProof.comparisons} comparisons at ${d.disjointnessProof.seedsPerStream} seeds per stream against ${d.disjointnessProof.priorPopulationsChecked} prior populations · total overlap ${d.disjointnessProof.totalOverlap}**

${Object.entries(d.disjointnessProof.overlaps).map(([k, v]) => `- ${k}: ${v}`).join("\n")}`);
  }

  if (has("historical-v5-runner-dry-run")) {
    const A = R("historical-v5-runner-dry-run"); const d = A.data;
    write("historical-v5-runner-dry-run.md", `${prov(A)}# Historical V5 runner — dry run

Runner version ${d.historicalHoldoutRunnerVersion} · module \`${d.runnerModule}\`
**${d.checks.length} checks · ${d.failedChecks.length} failed**

${d.exactCodePath}

Mock set: ${d.mockSet.members.join(", ")} — ${d.mockSet.source}. Contains a V5 id: ${yn(d.mockSet.containsV5Id)}.

| check | result | detail |
| --- | --- | --- |
${d.checks.map((c) => `| ${c.name} | ${c.pass ? "**PASS**" : "**FAIL**"} | ${c.detail} |`).join("\n")}

## Identity mismatch outcomes

${Object.entries(d.identityMismatchOutcomes).map(([k, v]) => `- changed \`${k}\` on resume → \`${v}\``).join("\n")}

## The one real evaluation

Fixture \`${d.realEvaluation.fixtureId}\` (non-holdout), ${d.realEvaluation.games} games:
share MAE ${d.realEvaluation.compositeShareMae} over ${Array.isArray(d.realEvaluation.supportedShareMetrics) ? d.realEvaluation.supportedShareMetrics.length : "?"} supported share metrics;
trait \`${d.realEvaluation.trait}\` scored **${d.realEvaluation.traitResult}** with diff ${d.realEvaluation.traitDiff} against margin ${d.realEvaluation.practicalMargin}.

Dual gate: statistically opposite ${yn(d.realEvaluation.dualGate.statisticallyOpposite)}, beyond margin ${yn(d.realEvaluation.dualGate.beyondPracticalMargin)} → hard fail ${yn(d.realEvaluation.dualGate.hardFail)}.

Structural: ${d.realEvaluation.invariantViolations} invariant violations, ${d.realEvaluation.ties} ties, replay exact ${yn(d.realEvaluation.replayExact)}.

## Access counts after the dry run

${Object.entries(d.accessCounts).map(([k, v]) => `- \`${k}\` — ${v}`).join("\n")}

Target access: ${d.targetAccess.usableTargetValues} usable, ${d.targetAccess.nullTargetValues} null, ${d.targetAccess.zeroFilled} zero-filled.`);
  }

  if (has("historical-holdout-v5-seal")) {
    const A = R("historical-holdout-v5-seal"); const d = A.data;
    write("historical-v5-seal.md", `${prov(A)}# Historical Holdout V5 — seal

**state \`${d.state}\` · access count ${d.accessCount} · sealHash \`${d.sealHash}\`**

Set \`${d.set}\` version ${d.setVersion}, sealed at commit \`${d.sealedAtCommit}\`.
Access log: \`${d.accessLogPath}\` — exists on disk: ${yn(d.accessLogExists)}.

## Candidate bound to this seal

| fact | value |
| --- | --- |
| candidate | \`${d.candidate.candidateId}\` (lock revision ${d.candidate.lockRevision}) |
| core hash | \`${d.candidate.coreHash}\` |
| parameter-set hash | \`${d.candidate.parameterSetHash}\` |
| possessionCalibrationVersion | ${d.candidate.possessionCalibrationVersion} |

## Bound hashes

${Object.entries(d.boundHashes).map(([k, v]) => `- \`${k}\` — \`${v}\``).join("\n")}

## The one authorized runner

\`${d.authorizedRunner.module}\` (version ${d.authorizedRunner.version})

\`\`\`bash
${d.authorizedRunner.command}
\`\`\`

${d.authorizedRunner.note}

## Failure behaviour

${Object.entries(d.failureBehaviour).map(([k, v]) => `- **${k}** — ${v}`).join("\n")}

## Seal integrity

${d.sealIntegrity.v5IdsChecked} V5 ids checked against ${d.sealIntegrity.outputArtifactsSearched} output-bearing artifacts: **${d.sealIntegrity.leaksFound} leaks**.
${d.sealIntegrity.carriedTeamsDefinedInPriorPool} carried teams appear in the pool corpus that defines them. ${d.sealIntegrity.note}

## Every seal

| set | status | access count |
| --- | --- | ---: |
${Object.entries(d.otherSeals).map(([k, v]) => `| \`${k}\` | ${v.status} | ${v.accessCount} |`).join("\n")}`);
  }

  if (has("historical-v5-readiness-final")) {
    const A = R("historical-v5-readiness-final"); const d = A.data;
    write("historical-v5-readiness-final.md", `${prov(A)}# Historical Holdout V5 — final readiness

**mayOpenInPhase6C4B2: ${d.mayOpenInPhase6C4B2}**

Candidate \`${d.candidate.candidateId}\` (lock revision ${d.candidate.lockRevision}) · ${d.candidate.calibrationStatus} · validation attempt ${d.candidate.validationAttemptStatus}
core \`${d.candidate.coreHash.slice(0, 16)}...\` · parameters \`${d.candidate.parameterSetHash.slice(0, 16)}...\` · calibration ${d.candidate.possessionCalibrationVersion}

| readiness fact | state |
| --- | --- |
${Object.entries(d).filter(([k, v]) => typeof v === "boolean" && k !== "mayOpenInPhase6C4B2").map(([k, v]) => `| ${k} | ${v ? "**READY**" : "**NOT READY**"} |`).join("\n")}

## Holdout state

| set | state | access count | verdict |
| --- | --- | ---: | --- |
${Object.entries(d.holdoutState).map(([k, v]) => `| \`${k}\` | ${v.state} | ${v.accessCount} | ${v.verdict ?? "—"} |`).join("\n")}

## Limitations

${d.limitations.map((l) => `### \`${l.id}\`\n\n${l.detail}`).join("\n\n")}`);

    write("phase-6c4b1-limitations.md", `${prov(A)}# Phase 6C4B1 — limitations

What this phase does NOT establish. Every entry is a measured property or a
recorded imprecision, not a hedge.

${d.limitations.map((l) => `### \`${l.id}\`\n\n${l.detail}`).join("\n\n")}

## What no artifact in this phase claims

Historical Holdout V5 has not been opened, run, or scored. Its access count is
${d.holdoutState.historicalHoldoutV5.accessCount} and its verdict is \`${d.holdoutState.historicalHoldoutV5.verdict}\`. Synthetic Stress
Holdout V2 has not been opened; its access count is ${d.holdoutState.syntheticStressHoldoutV2.accessCount}. Candidate 1 is
\`${d.candidate.calibrationStatus}\` — not holdout validated, not preview validated,
not production ready.`);
  }

  if (has("phase6c4b2-validation-package")) {
    const A = R("phase6c4b2-validation-package"); const d = A.data;
    write("phase-6c4b2-validation-package.md", `${prov(A)}# Phase 6C4B2 — validation package

Version ${d.phase6C4B2ValidationPackageVersion} · packageHash \`${d.packageHash}\`

## Candidate

| fact | value |
| --- | --- |
| candidate | \`${d.candidate.candidateId}\` (lock revision ${d.candidate.lockRevision}) |
| commit | \`${d.candidateCommit}\` |
| core hash | \`${d.candidate.coreHash}\` |
| parameter-set hash | \`${d.candidate.parameterSetHash}\` |
| possessionCalibrationVersion | ${d.candidate.possessionCalibrationVersion} |
| calibration status | ${d.candidate.calibrationStatus} |
| validation attempt | ${d.candidate.validationAttemptStatus} |

## Holdout

| fact | value |
| --- | --- |
| set | \`${d.holdout.set}\` version ${d.holdout.setVersion} |
| state | **${d.holdout.state}** |
| access count | **${d.holdout.accessCount}** |
${Object.entries(d.holdout).filter(([k]) => k.endsWith("Hash")).map(([k, v]) => `| ${k} | \`${v}\` |`).join("\n")}

## Runner

\`${d.runner.module}\` version ${d.runner.version}

\`\`\`bash
${d.runner.command}
\`\`\`

Expected volume: ${d.expectedRuntime.totalGames} games. ${d.expectedRuntime.estimateNote}.

## Access-event procedure

${d.accessEventProcedure.map((x) => `${x}`).join("\n")}

**Resume policy.** ${d.resumePolicy}

## Commands prepared (and NOT executed)

${Object.entries(d.commands).map(([k, v]) => `- \`${k}\`:\n  \`\`\`bash\n  ${v}\n  \`\`\``).join("\n")}

Executions in this phase: ${Object.entries(d.commandsExecutedInThisPhase).map(([k, v]) => `${k} ${v}`).join(" · ")}.

## Formal verdict rules

- pass → \`${d.formalVerdictRules.pass}\`
- fail → \`${d.formalVerdictRules.fail}\`
- invalid → \`${d.formalVerdictRules.invalid}\`

Trait rule: ${d.formalVerdictRules.traitRule}

Aggregate: minimum trait pass rate ${d.formalVerdictRules.aggregate.minTraitPassRate}, maximum hard fails ${d.formalVerdictRules.aggregate.maxHardFails}. ${d.formalVerdictRules.aggregate.perFixtureRule}. ${d.formalVerdictRules.aggregate.perEraRule}.

On failure: ${d.formalVerdictRules.onFail}

${d.formalVerdictRules.syntheticGate}

## Preview prerequisites

${d.previewPrerequisites.map((x) => `- ${x}`).join("\n")}

## Production isolation

${d.productionIsolationRequirements.map((x) => `- ${x}`).join("\n")}`);
  }

  console.log(written.length ? written.join("\n") : "no 6c4b1 artifacts yet");
}
