#!/usr/bin/env node
// ── Render the Phase 6C2C5 documents from artifacts ─────────────────────────
//   npm run calibration:c5:report
//
// This file is permitted to FORMAT and nothing else. It may not sum, count,
// average or derive. Every number it prints is read from an artifact field that
// the measuring command computed and hashed. Phase 6C2C4 shipped a readiness
// table whose counts summed to 59 against 53 active parameters because the
// numbers were written by hand in prose; a renderer that computes is a renderer
// that can disagree with its own artifact, so this one cannot compute.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt, countsTable, ARTIFACT_DIR_C6 } from "../../src/v3/calibration/artifacts.js";
import { versionOf } from "../../src/versions.js";
// Everything below runs ONLY as a command, never on import. A calibration script
// that executes at import time turns "read one constant from it" into "silently
// re-run the whole measurement" — which happened in Phase 6C2C2 to four scripts
// at once, and once more here, to these five.
if (import.meta.url === `file://${process.argv[1]}`) {

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });

const A = {
  coverage: readArtifact("targeted-fixture-coverage"),
  triage: readArtifact("no-effect-triage"),
  confounding: readArtifact("confounding-resolution"),
  scope: readArtifact("calibration-scope"),
  history: readArtifact("candidate-history"),
  comparison: readArtifact("candidate-comparison"),
  validation: readArtifact("validation-summary"),
  lock: readArtifact("candidate-lock"),
};

// Phase 6C2C6 superseded this artifact's `status` field. The artifact itself is
// preserved unedited — it is the record of what 6C2C5 concluded — but the
// RENDERED report must not keep presenting a superseded status as current.
// The correction is read from the c6 artifact, never hard-coded here.
const supersession = artifactExists("candidate-status-reconciliation", ARTIFACT_DIR_C6)
  ? readArtifact("candidate-status-reconciliation", ARTIFACT_DIR_C6).data
  : null;
const correctionBanner = supersession ? `> **SUPERSEDED — see \`candidate-status-reconciliation.md\`.**
>
> This document renders \`candidate-lock.json\`, whose \`status\` field said
> \`${supersession.supersedes.was}\`. Phase 6C2C6 found that status incoherent with
> the same artifact's own \`possessionCalibrationVersion: null\` and
> \`allEngineeringGatesPass: false\`, and split the single field into separate
> selection and lock claims:
>
> - \`candidateSelectionStatus\`: **${supersession.supersedes.nowSplitInto.candidateSelectionStatus}**
> - \`candidateLockStatus\`: **${supersession.supersedes.nowSplitInto.candidateLockStatus}**
> - \`calibrationStatus\`: **${supersession.supersedes.nowSplitInto.calibrationStatus}**
>
> The artifact below is retained unedited as the record of what 6C2C5 concluded.

` : "";

const provenance = (a) => [
  "<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->",
  `<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->`,
  `<!-- generated by: npm run calibration:c5:report  from: ${a.generationCommand} -->`,
  "",
].join("\n");

const written = [];
const write = (name, body) => {
  const path = `${DOCS}/${name}`;
  writeFileSync(path, `${body.trimEnd()}\n`);
  written.push(path);
};

// ── targeted mechanic coverage ──────────────────────────────────────────────
{
  const d = A.coverage.data;
  const c = d.coverage;
  const rows = d.parameters.map((p) =>
    `| \`${p.id}\` | ${p.module} | \`${p.contract.activationPredicate}\` | ${p.contract.context} | ${fmt(p.activatedPossessions, 0)} | ${p.activationMet ? "yes" : "**NO**"} |`).join("\n");
  write("targeted-mechanic-coverage.md", `${provenance(A.coverage)}# Targeted mechanic coverage

A parameter must be evaluated through the mechanic it controls. Labelling a
fixture by intent is not evidence, so each parameter below declares the
possession population that exercises it, and the count of possessions that
actually reached it.

- active parameters: **${fmt(c.activeParameters, 0)}**
- exercise contracts: **${fmt(c.exerciseContracts, 0)}**
- activation verified: **${fmt(c.activationVerified, 0)}**
- activation unmet: **${fmt(c.activationUnmet, 0)}**
- activated possessions: **${fmt(c.totalActivatedPossessions, 0)}**
- missing contracts: **${fmt(c.missingContracts, 0)}** · orphan contracts: **${fmt(c.orphanContracts, 0)}**
- reconciles: **${d.reconciliation.reconciles}**

| Parameter | Module | Activation predicate | Population | Activated possessions | Met |
| --- | --- | --- | --- | --- | --- |
${rows}
`);
}

// ── no-effect triage ────────────────────────────────────────────────────────
{
  const d = A.triage.data;
  const rows = d.parameters.filter((p) => p.wasPriorNoEffect).map((p) =>
    `| \`${p.id}\` | ${p.triage} | ${p.bestConditionalMetric ?? "—"} | ${fmt(p.bestConditionalSpan, 5)} | ${fmt(p.activatedPossessions, 0)} |`).join("\n");
  write("no-effect-triage.md", `${provenance(A.triage)}# No-effect triage

Phase 6C2C4 reported ${fmt(d.priorNoEffectCount, 0)} parameters with no
measurable effect, measured against game-level aggregates. A parameter that
governs a rare conditional context cannot appear in a season-long average, so
each of those was re-measured inside the population it actually governs.

${countsTable(d.triageCounts, { header: "Triage class" })}

\`RANGE_TOO_NARROW\` and \`TRUE_NO_EFFECT\` both resolve to a frozen default and
are merged in the readiness table; they are kept apart here because they are
different findings. One says the parameter does nothing; the other says its
registry range is too narrow for anything it does to show.

## Identifiability

${countsTable(d.identifiabilityCounts, { header: "Identifiability class" })}

## The ${fmt(d.priorNoEffectCount, 0)} prior no-effect parameters

| Parameter | Triage | Best conditional metric | Span across range | Activated possessions |
| --- | --- | --- | --- | --- |
${rows}
`);
}

// ── confounding resolution ──────────────────────────────────────────────────
{
  const d = A.confounding.data;
  const rows = d.groups.map((g) => {
    const r = g.results[0];
    return `| \`${g.a}\` ~ \`${g.b}\` | ${r.metric} | ${fmt(r.mainEffectA, 5)} | ${fmt(r.mainEffectB, 5)} | ${fmt(r.interaction, 5)} | ${g.resolution} |`;
  }).join("\n");
  const reasons = d.groups.map((g) => `**\`${g.a}\` ~ \`${g.b}\` → ${g.resolution}**\n\n${g.reason}`).join("\n\n");
  write("parameter-confounding-resolution-v3.md", `${provenance(A.confounding)}# Confounding resolution by 2x2 factorial

Correlated sparse signatures cannot tell "these are the same knob" from "these
happen to move the same metric". A factorial measures each parameter's effect at
both levels of the other, which separates the two.

Effect retention is why the rule tests magnitude and not only sign. A sign-only
rule passed a pair whose second member's effect collapsed from -28.0 to -0.33 —
retention 0.012. An effect that survives in sign and vanishes in magnitude is
not independently identifiable.

${countsTable(d.counts, { header: "Resolution" })}

- reconciles: **${d.reconciliation.reconciles}**

| Pair | Primary metric | Main effect A | Main effect B | Interaction | Resolution |
| --- | --- | --- | --- | --- | --- |
${rows}

## Reasoning, per pair

${reasons}
`);
}

// ── readiness ───────────────────────────────────────────────────────────────
// countsTable() appends a TOTAL row, which is meaningful for counts of
// parameters and meaningless for cap fractions. The caps table is therefore
// formatted directly: summing 1.0 + 0.1 + 0.2 to "1.3" would be a number that
// looks computed and means nothing.
{
  const d = A.triage.data;
  write("calibration-readiness-v3.md", `${provenance(A.triage)}# Calibration readiness v3

Every active runtime parameter carries exactly one readiness class, and the
classes sum to the active parameter count. That sum is checked by the measuring
command, not asserted here.

${countsTable(d.readinessCounts, { header: "Readiness class" })}

- eligible for search: **${fmt(d.eligibleForSearch, 0)}**
- frozen: **${fmt(d.frozen, 0)}**
- all reconciliations pass: **${d.allReconcile}**

## Movement caps

| Readiness class | Cap (fraction of registry range) |
| --- | --- |
${Object.entries(d.movementCaps).map(([k, v]) => `| \`${k}\` | ${fmt(v, 3)} |`).join("\n")}

A frozen parameter has a cap of exactly zero. The caps are tied to the readiness
class rather than left to judgement, because the temptation at the search stage
is to widen a bound until a parameter looks identifiable.
`);
}

// ── calibration scope ───────────────────────────────────────────────────────
{
  const d = A.scope.data;
  const rows = d.eligibleParameters.map((p) =>
    `| \`${p.id}\` | ${fmt(p.defaultValue, 4)} | ${fmt(p.searchBounds.lo, 4)} – ${fmt(p.searchBounds.hi, 4)} | ${fmt(p.movementCapFractionOfRange, 2)} | ${p.readiness} | ${p.support} |`).join("\n");
  write("targeted-calibration-scope.md", `${provenance(A.scope)}# Targeted calibration scope

Frozen and hashed BEFORE the search ran. That ordering is what makes "no change
beat the defaults" a finding rather than an excuse.

- active parameters: **${fmt(d.activeParameterCount, 0)}**
- eligible for search: **${fmt(d.eligibleCount, 0)}**
- frozen: **${fmt(d.frozenCount, 0)}**
- reconciles: **${d.reconciliation.reconciles}**

## Objective

${d.objective.statistic}

- target class: \`${d.objective.targetClass}\`
- direction: ${d.objective.direction}
- normalisation: ${d.objective.normalisation}
- matchup: ${d.objective.matchup}

**Why this objective.** ${d.objective.whyThisObjective}

**Limitations.**
${d.objective.limitations.map((l) => `- ${l}`).join("\n")}

## Folds

- grouping: ${d.folds.grouping}
- leak free: ${d.folds.leakFree}
- tuning: folds ${d.folds.tuningFolds.join(", ")} — ${fmt(d.folds.tuningFixtureCount, 0)} fixtures
- validation: folds ${d.folds.validationFolds.join(", ")} — ${fmt(d.folds.validationFixtureCount, 0)} fixtures

## Thresholds

- minimum tuning improvement: ${fmt(d.thresholds.minTuningImprovement, 5)}
- maximum validation degradation: ${fmt(d.thresholds.maxValidationDegradation, 4)} relative
- Candidate 0 always competes: ${d.thresholds.candidateZeroAlwaysCompetes}

${d.thresholds.note}

## Eligible parameters

| Parameter | Default | Search bounds | Cap (fraction of range) | Readiness | Support |
| --- | --- | --- | --- | --- | --- |
${rows}
`);
}

// ── candidate history ───────────────────────────────────────────────────────
{
  const d = A.history.data;
  const adj = d.adjudicability;
  const probe = Object.entries(adj.perParameter).map(([id, v]) =>
    `| \`${id}\` | ${fmt(v.registryMin, 4)} | ${fmt(v.registryMax, 4)} | ${fmt(v.cellsDiffering, 0)} / ${fmt(v.cellsTotal, 0)} | ${v.objectiveAdjudicable ? "yes" : "**no**"} |`).join("\n");
  const top = d.history.filter((h) => h.candidateId !== "C0")
    .slice().sort((a, b) => (b.tuningGain ?? -Infinity) - (a.tuningGain ?? -Infinity)).slice(0, 12)
    .map((h) => `| ${h.candidateId} | \`${h.label}\` | ${fmt(h.tuningMae, 5)} | ${fmt(h.tuningGain, 5)} | ${fmt(h.rawP, 4)} | ${fmt(h.holmAdjustedP, 4)} | ${h.accepted ? "**accepted**" : "rejected"} |`).join("\n");
  write("candidate-history.md", `${provenance(A.history)}# Candidate history

- on-grid candidates: **${fmt(d.changedCandidates, 0)}** plus Candidate 0
- clearing the practical floor: **${fmt(d.familyDiagnostics.candidatesClearingPracticalFloor, 0)}**
- family-wise significant: **${fmt(d.familyDiagnostics.candidatesFamilyWiseSignificant, 0)}**
- accepted: **${fmt(d.acceptedCount, 0)}**
- rejected: **${fmt(d.rejectedCount, 0)}**
- best Holm-adjusted p: **${fmt(d.familyDiagnostics.bestHolmAdjustedP, 4)}** at alpha ${fmt(d.policy.familyWiseAlpha, 3)} over a family of ${fmt(d.familySize, 0)}
- outcome: **${d.outcome}**

Candidate 0 is the wired default set. Acceptance required all of
${d.policy.acceptanceRequires.join(", ")}.

## Superseded first run

${d.supersedes.reason} See \`${d.supersedes.artifact}\`.

## Adjudicability

${adj.note}

**${fmt(adj.visibleToObjective, 0)}** of the eligible parameters are visible to
the objective; **${fmt(adj.blindToObjective, 0)}** are not. ${adj.blindConsequence}

| Parameter | Registry min | Registry max | Objective cells differing | Adjudicable |
| --- | --- | --- | --- | --- |
${probe}

## Strongest twelve candidates by tuning gain

| Candidate | Change | Tuning MAE | Gain | Raw p | Holm-adjusted p | Outcome |
| --- | --- | --- | --- | --- | --- | --- |
${top}
`);
}

// ── head-to-head ────────────────────────────────────────────────────────────
{
  const d = A.comparison.data;
  const rows = d.freshSeedResults.map((r) =>
    `| ${r.set} | ${fmt(r.fixtures, 0)} | ${fmt(r.candidateZeroMae, 5)} | ${fmt(r.contenderMae, 5)} | ${fmt(r.gain, 5)} | ${fmt(r.t, 4)} | ${fmt(r.rawP, 4)} |`).join("\n");
  write("candidate-comparison.md", `${provenance(A.comparison)}# Head-to-head: Candidate 0 versus the strongest contender

- outcome: **${d.outcome}**
- an accepted changed candidate exists: **${d.acceptedChangedCandidateExists}**

${d.whyNoAcceptedCandidate}

## The promoted contender

\`${d.contenderPromotedForTransparency.label}\` (${d.contenderPromotedForTransparency.candidateId}) had the
largest tuning gain of any adjudicable candidate, at
${fmt(d.contenderPromotedForTransparency.searchTuningGain, 5)}. It was rejected:
${d.contenderPromotedForTransparency.rejectedReason}

It is re-measured here on a confirmation seed block at offset
${fmt(d.confirmationSeedOffset, 0)}, disjoint from the seeds the search used. The
contender was selected BY those search seeds, so re-scoring it on them would
re-measure the selection rather than the effect.

| Fixture set | Fixtures | Candidate 0 MAE | Contender MAE | Gain | Paired t | p |
| --- | --- | --- | --- | --- | --- | --- |
${rows}

- gain retained on fresh seeds: **${fmt(d.gainRetainedOnFreshSeeds, 4)}**
- holds up on fresh seeds: **${d.contenderHoldsUpOnFreshSeeds}**

${d.interpretation}

**Winner: ${d.winner}.**
`);
}

// ── validation ──────────────────────────────────────────────────────────────
{
  const d = A.validation.data;
  const s = (n) => d.sections.find((x) => x.name === n);
  const modes = s("competitionModes");
  const strat = s("competitionStructureStratified");
  const tails = s("statisticalTails");
  const hist = s("historicalCalibrationV3");
  const hold = s("holdoutDiscipline");
  const modeRows = modes.modes.map((m) =>
    `| ${m.mode} | ${fmt(m.games, 0)} | ${fmt(m.invariantViolations, 0)} |`).join("\n");
  const stratRows = ["balanced", "mismatched", "mirror"].map((k) =>
    `| ${k} | ${fmt(strat.seriesCountByPairing[k], 0)} | \`${JSON.stringify(strat.seriesLengthByPairing[k])}\` | ${fmt(strat.sweepRates[k], 4)} |`).join("\n");
  write("candidate-validation-summary.md", `${provenance(A.validation)}# Validation summary

- candidate: **${d.candidate}**
- parameter set hash: \`${d.parameterSetHash}\`
- parameter set status: \`${d.parameterSetStatus}\`
- games simulated: **${fmt(d.totalGamesSimulated, 0)}**
- all invariants clean: **${d.allInvariantsClean}**
- gates passed: **${d.gatesPassed}**

## Historical calibration v3

- tuning MAE ${fmt(hist.tuningMae, 5)} over ${fmt(hist.tuningFixtures, 0)} fixtures
- validation MAE ${fmt(hist.validationMae, 5)} over ${fmt(hist.validationFixtures, 0)} fixtures
- gap ${fmt(hist.gap, 5)}
- overfitting assessment: \`${hist.overfittingAssessment}\`

${hist.overfittingNote}

## Statistical tails

${fmt(tails.games, 0)} games. Invariant violations **${fmt(tails.invariantViolations, 0)}**.
Score percentiles: p01 ${fmt(tails.scoreP01, 0)}, p50 ${fmt(tails.scoreP50, 0)},
p99 ${fmt(tails.scoreP99, 0)}, range ${fmt(tails.scoreMin, 0)}–${fmt(tails.scoreMax, 0)}.
Impossible scores **${fmt(tails.impossibleScores, 0)}**.
Mean combined ${fmt(tails.meanCombined, 2)}, mean possessions ${fmt(tails.meanPossessions, 2)}.

## Competition modes

| Mode | Games | Invariant violations |
| --- | --- | --- |
${modeRows}

Totals: **${fmt(modes.totalGames, 0)}** games, **${fmt(modes.totalInvariantViolations, 0)}** violations.

## Competition structure, stratified

${strat.interpretation}

| Pairing | Series | Length distribution | Sweep rate |
| --- | --- | --- | --- |
${stratRows}

Mirror seasons: mean gold wins ${fmt(strat.mirrorSeasonMeanGoldWins, 2)} of 82,
against an unbiased ${fmt(strat.mirrorSeasonUnbiasedMean, 0)}.

${strat.realWorldReference}

## Holdout discipline

- historical holdout v3: ${fmt(hold.historicalHoldoutV3.members, 0)} members, access count **${fmt(hold.historicalHoldoutV3.accessCount, 0)}**, \`${hold.historicalHoldoutV3.status}\`
- synthetic stress holdout v2: ${fmt(hold.syntheticStressHoldoutV2.members, 0)} members, access count **${fmt(hold.syntheticStressHoldoutV2.accessCount, 0)}**, \`${hold.syntheticStressHoldoutV2.status}\`
- sealed members touched during validation: **${fmt(hold.sealedMembersTouchedDuringValidation.length, 0)}**
- verified: **${hold.verified}**
`);
}

// ── candidate lock ──────────────────────────────────────────────────────────
{
  const d = A.lock.data;
  const gateRows = d.engineeringGates.map((g) =>
    `| \`${g.name}\` | ${g.pass ? "PASS" : "**FAIL**"} | ${g.detail} |`).join("\n");
  const carried = d.carriedForwardFailures.length
    ? d.carriedForwardFailures.map((c) => `### \`${c.gate}\`\n\n${c.detail}\n\n- scope: ${c.scope}\n- predates this phase: **${c.predatesThisPhase}**\n- must be resolved before: ${c.mustBeResolvedBefore.map((x) => `${x}`).join(", ")}`).join("\n\n")
    : "None.";
  const pv = d.probabilityValidation;
  write("candidate-lock.md", `${provenance(A.lock)}${correctionBanner}# Candidate lock

- locked candidate: **${d.lockedCandidateId}**
- status: **\`${d.status}\`**
- parameter changes: **${fmt(d.changedParameterCount, 0)}**
- active parameters: **${fmt(d.activeParameterCount, 0)}**
- parameter set hash: \`${d.parameterSetHash}\`
- parameter set status: \`${d.parameterSetStatus}\`
- manifest hash: \`${d.manifestHash}\`

${d.statusMeaning}

## What this lock does NOT claim

${d.isNotClaiming.map((x) => `- ${x}`).join("\n")}

## Why no parameter changed

${d.whyNoChange}

## Outcome

| Measure | Value |
| --- | --- |
| on-grid candidates | ${fmt(d.outcome.onGridCandidates, 0)} |
| family size | ${fmt(d.outcome.familySize, 0)} |
| clearing the practical floor | ${fmt(d.outcome.clearingPracticalFloor, 0)} |
| family-wise significant | ${fmt(d.outcome.familyWiseSignificant, 0)} |
| best Holm-adjusted p | ${fmt(d.outcome.bestHolmAdjustedP, 4)} |
| accepted | ${fmt(d.outcome.accepted, 0)} |
| parameters adjudicated by the objective | ${fmt(d.outcome.adjudicatedParameters, 0)} |
| parameters the objective cannot see | ${fmt(d.outcome.unadjudicableParameters, 0)} |
| contender gain retained on fresh seeds | ${fmt(d.outcome.contenderRetainedOnFreshSeeds, 4)} |

Parameters the objective cannot adjudicate:
${d.outcome.unadjudicableList.map((x) => `- \`${x}\``).join("\n")}

## Content-addressed inputs

| Artifact | Hash |
| --- | --- |
| calibration scope | \`${d.calibrationScopeHash}\` |
| candidate history | \`${d.candidateHistoryHash}\` |
| candidate comparison | \`${d.candidateComparisonHash}\` |
| validation summary | \`${d.validationSummaryHash}\` |
| targeted fixture coverage | \`${d.targetedFixtureCoverageHash}\` |
| no-effect triage | \`${d.noEffectTriageHash}\` |
| confounding resolution | \`${d.confoundingResolutionHash}\` |
| superseded first search | \`${d.supersededCandidateHistoryHash}\` |
| side symmetry | \`${d.sideSymmetryArtifactHash}\` |
| probability validation | \`${d.probabilityArtifactHash}\` |

${d.immutability}

## Engineering gates

- candidate-lock gates pass: **${d.candidateLockGatesPass}**
- all gates pass: **${d.allEngineeringGatesPass}**

| Gate | Verdict | Detail |
| --- | --- | --- |
${gateRows}

${d.gatePartitionDisclosure ? `**Disclosure.** ${d.gatePartitionDisclosure}` : ""}

## Carried-forward failures

${carried}

## Monte Carlo probability revalidation

- version: \`${pv.version}\` · cells ${fmt(pv.cells, 0)} · games per cell ${fmt(pv.gamesPerCell, 0)}
- all gates pass: **${pv.allGatesPass}**
- failing: ${pv.failingGates.map((f) => `\`${f}\``).join(", ") || "none"}
- max absolute per-cell side bias: **${fmt(pv.sideBias.maxAbsolutePerCell, 4)}** against a frozen threshold of ${fmt(pv.frozenThreshold, 3)}
- mean across cells ${fmt(pv.sideBias.meanAcrossCells, 4)} ± ${fmt(pv.sideBias.standardError, 4)}, t ${fmt(pv.sideBias.tStatistic, 4)}, systematic **${pv.sideBias.systematic}**
- per-cell standard error at this sample size: ${fmt(pv.sideBias.perCellStandardErrorAtSampleSize, 4)}

${pv.preExistingEvidence}

${pv.notCausedByThisPhase}

**On the gate's power.** ${pv.multiplicityContext}

Frozen threshold unchanged: **${pv.thresholdUnchanged}**.

${pv.aggregateContrast}
`);
}

console.log(`RENDERED ${written.length} documents from ${Object.keys(A).length} artifacts`);
for (const p of written) console.log(`  ${p}`);
console.log(`\nrenderer version ${versionOf("calibrationReportRendererVersion")} — formats only, never computes`);
}
