#!/usr/bin/env node
// ── Render the Phase 6C2C6 documents from artifacts ─────────────────────────
//   npm run calibration:c6:report
//
// Formats only. Never sums, counts, averages or derives. Every number printed
// here is read from a field that a measuring command computed and hashed.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt, countsTable, ARTIFACT_DIR_C6 } from "../../src/v3/calibration/artifacts.js";
import { versionOf } from "../../src/versions.js";
// Everything below runs ONLY as a command, never on import.
if (import.meta.url === `file://${process.argv[1]}`) {

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const R = (n) => readArtifact(n, ARTIFACT_DIR_C6);
const has = (n) => artifactExists(n, ARTIFACT_DIR_C6);

const provenance = (a) => [
  "<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->",
  `<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->`,
  `<!-- generated by: npm run calibration:c6:report  from: ${a.generationCommand} -->`,
  "",
].join("\n");

const written = [];
const write = (name, body) => { writeFileSync(`${DOCS}/${name}`, `${body.trimEnd()}\n`); written.push(`${DOCS}/${name}`); };

// ── candidate status reconciliation ─────────────────────────────────────────
{
  const A = R("candidate-status-reconciliation");
  const d = A.data;
  const c = d.contradictionFound;
  const t = d.truthfulCurrentState;
  const vio = c.violations.map((v) => `| \`${v.invariant}\` | ${v.problem} |`).join("\n");
  write("candidate-status-reconciliation.md", `${provenance(A)}# Candidate status reconciliation

Phase 6C2C5 published a locked status for a candidate that was not locked. This
records what it published, why the status model allowed it, and what the state
truthfully is.

## The contradiction

**Detected: ${c.detected}.**

${c.where}

| Field | Published value |
| --- | --- |
| \`status\` | \`${c.publishedState.status}\` |
| \`versions.possessionCalibrationVersion\` | \`${c.publishedState.possessionCalibrationVersion}\` |
| \`allEngineeringGatesPass\` | ${c.publishedState.allEngineeringGatesPass} |
| \`candidateLockGatesPass\` | ${c.publishedState.candidateLockGatesPass} |
| had a \`candidateSelectionStatus\` field | ${c.publishedState.hadSelectionStatusField} |
| had a \`candidateLockStatus\` field | ${c.publishedState.hadLockStatusField} |

Invariants the published state violates:

| Invariant | Problem |
| --- | --- |
${vio}

### Root cause

${c.rootCause}

### What 6C2C5 did get right

${c.notConcealed}

## Truthful current state

| Field | Value |
| --- | --- |
| \`candidateId\` | ${t.candidateId} |
| \`candidateSelectionStatus\` | **${t.candidateSelectionStatus}** |
| \`candidateLockStatus\` | **${t.candidateLockStatus}** |
| \`calibrationStatus\` | **${t.calibrationStatus}** |
| \`possessionCalibrationVersion\` | \`${t.possessionCalibrationVersion}\` |
| \`parameterChanges\` | ${fmt(t.parameterChanges, 0)} |
| values equal registry defaults | ${t.parameterValuesEqualRegistryDefaults} |
| \`parameterSetHash\` | \`${t.parameterSetHash}\` |
| \`parameterSetStatus\` | \`${t.parameterSetStatus}\` |
| \`lockManifestPresent\` | ${t.lockManifestPresent} |

Lock blockers:
${t.candidateLockBlockers.length ? t.candidateLockBlockers.map((b) => `- \`${b}\``).join("\n") : "- (none)"}

**Coherent: ${d.currentStateCoherent}.** ${d.currentStateViolations.length ? "Violations remain." : "No invariant is violated."}

### Selection reason

${t.candidateSelectionReason}

## Invariants enforced

${d.statusInvariants.map((i) => `- \`${i}\``).join("\n")}

Reconciles: **${d.reconciliation.reconciles}** (${fmt(d.reconciliation.sum, 0)} of ${fmt(d.reconciliation.expectedTotal, 0)} invariants accounted for).

## Artifact provenance

${fmt(d.artifactVerification.checked, 0)} Phase 6C2C5 artifacts checked, **${fmt(d.artifactVerification.invalid, 0)}** invalid.

The Phase 6C2C5 lock gate tested \`verifyArtifact(n).ok !== false\`.
\`verifyArtifact\` returns \`valid\`, never \`ok\`, so \`undefined !== false\` made that
gate unfailable. This check reads \`valid\`.

## Supersession

\`${d.supersedes.artifact}\` field \`${d.supersedes.field}\` was \`${d.supersedes.was}\`,
now split into \`candidateSelectionStatus\` = **${d.supersedes.nowSplitInto.candidateSelectionStatus}**,
\`candidateLockStatus\` = **${d.supersedes.nowSplitInto.candidateLockStatus}**,
\`calibrationStatus\` = **${d.supersedes.nowSplitInto.calibrationStatus}**.

Original preserved unedited: **${d.supersedes.preserved}**.
`);
}

console.log(`RENDERED ${written.length} document(s)`);
for (const p of written) console.log(`  ${p}`);
console.log(`\nrenderer version ${versionOf("calibrationReportRendererVersion")} — formats only, never computes`);
}
