#!/usr/bin/env node
// ── Render the Phase 6C2C6 documents from artifacts ─────────────────────────
//   npm run calibration:c6:report
//
// Formats only. Never sums, counts, averages or derives. Every number printed
// here is read from a field that a measuring command computed and hashed.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt, countsTable, ARTIFACT_DIR_C6 } from "../../src/v3/calibration/artifacts.js";
import { versionOf } from "../../src/versions.js";
// Everything below runs ONLY as a command, never on import.
if (import.meta.url === `file://${process.argv[1]}`) {

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const R = (n) => readArtifact(n, ARTIFACT_DIR_C6);
const has = (n) => artifactExists(n, ARTIFACT_DIR_C6);

const provenance = (a) => [
  "<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->",
  `<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->`,
  `<!-- generated by: npm run calibration:c6:report  from: ${a.generationCommand} -->`,
  "",
].join("\n");

const written = [];
const write = (name, body) => { writeFileSync(`${DOCS}/${name}`, `${body.trimEnd()}\n`); written.push(`${DOCS}/${name}`); };

// ── candidate status reconciliation ─────────────────────────────────────────
{
  const A = R("candidate-status-reconciliation");
  const d = A.data;
  const c = d.contradictionFound;
  const t = d.truthfulCurrentState;
  const vio = c.violations.map((v) => `| \`${v.invariant}\` | ${v.problem} |`).join("\n");
  write("candidate-status-reconciliation.md", `${provenance(A)}# Candidate status reconciliation

Phase 6C2C5 published a locked status for a candidate that was not locked. This
records what it published, why the status model allowed it, and what the state
truthfully is.

## The contradiction

**Detected: ${c.detected}.**

${c.where}

| Field | Published value |
| --- | --- |
| \`status\` | \`${c.publishedState.status}\` |
| \`versions.possessionCalibrationVersion\` | \`${c.publishedState.possessionCalibrationVersion}\` |
| \`allEngineeringGatesPass\` | ${c.publishedState.allEngineeringGatesPass} |
| \`candidateLockGatesPass\` | ${c.publishedState.candidateLockGatesPass} |
| had a \`candidateSelectionStatus\` field | ${c.publishedState.hadSelectionStatusField} |
| had a \`candidateLockStatus\` field | ${c.publishedState.hadLockStatusField} |

Invariants the published state violates:

| Invariant | Problem |
| --- | --- |
${vio}

### Root cause

${c.rootCause}

### What 6C2C5 did get right

${c.notConcealed}

## Truthful current state

| Field | Value |
| --- | --- |
| \`candidateId\` | ${t.candidateId} |
| \`candidateSelectionStatus\` | **${t.candidateSelectionStatus}** |
| \`candidateLockStatus\` | **${t.candidateLockStatus}** |
| \`calibrationStatus\` | **${t.calibrationStatus}** |
| \`possessionCalibrationVersion\` | \`${t.possessionCalibrationVersion}\` |
| \`parameterChanges\` | ${fmt(t.parameterChanges, 0)} |
| values equal registry defaults | ${t.parameterValuesEqualRegistryDefaults} |
| \`parameterSetHash\` | \`${t.parameterSetHash}\` |
| \`parameterSetStatus\` | \`${t.parameterSetStatus}\` |
| \`lockManifestPresent\` | ${t.lockManifestPresent} |

Lock blockers:
${t.candidateLockBlockers.length ? t.candidateLockBlockers.map((b) => `- \`${b}\``).join("\n") : "- (none)"}

**Coherent: ${d.currentStateCoherent}.** ${d.currentStateViolations.length ? "Violations remain." : "No invariant is violated."}

### Selection reason

${t.candidateSelectionReason}

## Invariants enforced

${d.statusInvariants.map((i) => `- \`${i}\``).join("\n")}

Reconciles: **${d.reconciliation.reconciles}** (${fmt(d.reconciliation.sum, 0)} of ${fmt(d.reconciliation.expectedTotal, 0)} invariants accounted for).

## Artifact provenance

${fmt(d.artifactVerification.checked, 0)} Phase 6C2C5 artifacts checked, **${fmt(d.artifactVerification.invalid, 0)}** invalid.

The Phase 6C2C5 lock gate tested \`verifyArtifact(n).ok !== false\`.
\`verifyArtifact\` returns \`valid\`, never \`ok\`, so \`undefined !== false\` made that
gate unfailable. This check reads \`valid\`.

## Supersession

\`${d.supersedes.artifact}\` field \`${d.supersedes.field}\` was \`${d.supersedes.was}\`,
now split into \`candidateSelectionStatus\` = **${d.supersedes.nowSplitInto.candidateSelectionStatus}**,
\`candidateLockStatus\` = **${d.supersedes.nowSplitInto.candidateLockStatus}**,
\`calibrationStatus\` = **${d.supersedes.nowSplitInto.calibrationStatus}**.

Original preserved unedited: **${d.supersedes.preserved}**.
`);
}

// ── side-bias policy v2 ─────────────────────────────────────────────────────
{
  const A = R("probability-side-bias-policy-v2"); const d = A.data; const P = d.policy;
  write("probability-side-bias-policy-v2.md", `${provenance(A)}# Probability side-bias policy v2

Frozen before any fresh result. **policyHash \`${d.policyHash}\`.**

## What v1 was, and why it could not answer its own question

v1 compared a per-cell **point estimate** against a fixed ${P.supersedes.v1Threshold},
with no multiplicity control across the family and a standard error taken from
the wrong design. It failed on one cell at ${P.supersedes.v1Observation} and could not
say whether that cell was biased or unlucky, because it never expressed
uncertainty about the quantity it gated.

## The scale correction, disclosed

${P.EFFECT.supersedesV1Statistic}.

${P.MARGINS.perCellNote}

## The effect

- **${P.EFFECT.name}** (\`${P.EFFECT.symbol}\`): ${P.EFFECT.estimator}
- per-pair observation: ${P.EFFECT.perPairObservation}
- support: ${JSON.stringify(P.EFFECT.support)}
- positive means: ${P.EFFECT.positiveMeaning}
- negative means: ${P.EFFECT.negativeMeaning}
- mirror case: ${P.EFFECT.mirrorEquivalent}

${P.EFFECT.perspectiveRule}

## Margins

| Margin | Value |
| --- | --- |
| per-cell practical equivalence | +/-${fmt(P.MARGINS.perCell, 3)} |
| aggregate systematic bias | +/-${fmt(P.MARGINS.aggregate, 3)} |

${P.MARGINS.notDerivedFromObservation}

## Confidence

- primary: ${P.CONFIDENCE.primary}
- secondary: ${P.CONFIDENCE.secondary}
- agreement required: ${P.CONFIDENCE.agreementRequired}

${P.CONFIDENCE.whyNotTwoIndependentProportions}

## Family-wise control

Method **${P.FAMILY_WISE.method}** at alpha ${fmt(P.FAMILY_WISE.alpha, 3)}, applied to ${P.FAMILY_WISE.appliedTo}.

- equivalence direction: ${P.FAMILY_WISE.equivalenceDirection}
- detection direction: ${P.FAMILY_WISE.detectionDirection}

${P.FAMILY_WISE.bothRequired}

## Sample ladder

${P.SAMPLE_LADDER.stages.map((x) => `- stage ${x.stage}: ${fmt(x.cumulativePairs, 0)} cumulative pairs`).join("\n")}

${P.SAMPLE_LADDER.cumulativeNote}

${P.SAMPLE_LADDER.maximumJustification}

## Stopping rules

- ${P.STOPPING.equivalenceEstablished}
- ${P.STOPPING.materialBiasEstablished}
- ${P.STOPPING.maximumReached}

${P.STOPPING.uniformEscalation}

Forbidden:
${P.STOPPING.forbidden.map((x) => `- ${x}`).join("\n")}

## Failure semantics

${Object.entries(P.FAILURE_SEMANTICS).map(([k, v]) => `- \`${k}\`: ${v}`).join("\n")}

## Seed manifest

| Field | Value |
| --- | --- |
| version | ${d.seedManifest.probabilitySideBiasSeedSetVersion} |
| domain | \`${d.seedManifest.domain}\` |
| master commitment | \`${d.seedManifest.masterCommitment}\` |
| maximum pairs | ${fmt(d.seedManifest.maximumPairs, 0)} |
| distinct seeds | ${fmt(d.seedManifest.distinctSeeds, 0)} |
| all distinct | ${d.seedManifest.allDistinct} |
| total overlap with prior domains | **${fmt(d.seedManifest.totalOverlap, 0)}** |
| manifest hash | \`${d.seedManifest.manifestHash}\` |

${Object.entries(d.seedManifest.overlapWithPriorDomains).map(([k, v]) => `- \`${k}\`: ${fmt(v, 0)}`).join("\n")}

## Frozen cell family

${fmt(d.cellFamily.count, 0)} cells, reconciles **${d.cellFamily.reconciliation.reconciles}**, holdout contamination **${d.cellFamily.holdoutContamination}**.

${countsTable(d.cellFamily.byKind, { header: "Kind" })}

${countsTable(d.cellFamily.byEra, { header: "Era" })}

${d.cellFamily.eraCoverageNote}

| Coverage requirement | Cells |
| --- | --- |
| exact mirrors | ${fmt(d.coverageAgainstBriefRequirements.exactMirrors, 0)} |
| non-mirror pairs | ${fmt(d.coverageAgainstBriefRequirements.nonMirrorPairs, 0)} |
| zone-capable | ${fmt(d.coverageAgainstBriefRequirements.zoneCapable, 0)} |
| shooting advantage | ${fmt(d.coverageAgainstBriefRequirements.shootingAdvantage, 0)} |
| size advantage | ${fmt(d.coverageAgainstBriefRequirements.sizeAdvantage, 0)} |
| defensive advantage | ${fmt(d.coverageAgainstBriefRequirements.defensiveAdvantage, 0)} |
| balanced vs higher-OVR | ${fmt(d.coverageAgainstBriefRequirements.balancedVersusHigherOvr, 0)} |
| distinct eras | ${fmt(d.coverageAgainstBriefRequirements.distinctEras, 0)} |

${d.coverageAgainstBriefRequirements.note}
`);
}

// ── prior failing cell ──────────────────────────────────────────────────────
{
  const A = R("prior-failing-cell"); const d = A.data;
  write("prior-failing-probability-cell.md", `${provenance(A)}# The prior failing probability cell

Read from the Phase 6C2C5 artifact, not inferred from prose.

| Field | Value |
| --- | --- |
| cell | \`${d.cellId}\` |
| index in family | ${fmt(d.indexInFamily, 0)} of ${fmt(d.familySize, 0)} |
| era style | ${d.eraStyleId} |
| team A | \`${d.teamA.id}\` (coach \`${d.teamA.coach}\`) |
| team B | \`${d.teamB.id}\` (coach \`${d.teamB.coach}\`) |
| sample tier | ${d.sampleTier} |
| estimator sample | ${fmt(d.estimatorSampleCount, 0)} games = ${fmt(d.estimatorPairs, 0)} paired seeds |
| empirical validation games | ${fmt(d.empiricalValidationGames, 0)} |
| prediction seed set | ${d.predictionSeedSetVersion} |
| parameter set hash | \`${d.parameterSetHash}\` |
| predicted | ${fmt(d.predicted, 4)} |
| empirical | ${fmt(d.empirical, 4)} |

## Rosters

- **${d.teamA.id}**: ${d.teamA.five.map((x) => `\`${x}\``).join(", ")}
- **${d.teamB.id}**: ${d.teamB.five.map((x) => `\`${x}\``).join(", ")}

## Raw orientation results

| Field | Value |
| --- | --- |
| perspective team | \`${d.rawOrientationResults.perspectiveTeam}\` |
| perspective wins as Gold | ${fmt(d.rawOrientationResults.firstAsGoldWinRate, 4)} |
| perspective wins as Blue | ${fmt(d.rawOrientationResults.firstAsBlueWinRate, 4)} |
| Gold-slot win rate | ${fmt(d.rawOrientationResults.goldOrientationRate, 4)} |
| Blue-slot win rate | ${fmt(d.rawOrientationResults.blueOrientationRate, 4)} |

## The v1 gate, and what its number meant

| Field | Value |
| --- | --- |
| v1 definition | \`${d.v1SideBiasDefinition}\` |
| v1 point estimate | ${fmt(d.v1PointEstimate, 4)} |
| v1 reported standard error | ${fmt(d.v1ReportedStandardError, 5)} |
| v1 threshold | ${fmt(d.v1Threshold, 3)} |
| v1 gate result | **${d.v1GateResult}** |
| corrected paired effect | ${fmt(d.correctedPairedEffect, 4)} |
| scale relationship | ${d.scaleRelationship} |
| scale verified | **${d.scaleVerified}** |
`);
}

// ── orientation audit ───────────────────────────────────────────────────────
{
  const A = R("probability-orientation-audit"); const d = A.data;
  const rows = d.semanticChecks.map((c) => `| \`${c.name}\` | ${c.pass ? "OK" : "**DEFECT**"} | ${c.detail} |`).join("\n");
  const adj = d.adjacentControls.map((c) => `| ${c.label} | \`${c.teamA}\` vs \`${c.teamB}\` | ${c.era} | ${fmt(c.pairs, 0)} | ${fmt(c.delta, 5)} | [${fmt(c.waldInterval.lower, 5)}, ${fmt(c.waldInterval.upper, 5)}] | ${fmt(c.p, 4)} |`).join("\n");
  const ctl = d.actualGameControl; const w = ctl.winEffect;
  write("probability-orientation-audit.md", `${provenance(A)}# Probability orientation audit

## Three questions, kept separate

${Object.entries(d.threeQuestionsSeparated).map(([k, v]) => `- **${k}**: ${v}`).join("\n")}

## Semantic checks

${fmt(d.checksPassed, 0)} pass, **${fmt(d.checksFailed, 0)}** defects.

| Check | Verdict | Detail |
| --- | --- | --- |
${rows}

### Defects and their reach

Found: ${d.harnessDefectsFound.map((x) => `\`${x}\``).join(", ") || "none"}.

Affects a reported number: **${d.harnessDefectsAffectReportedNumbers}**.

${d.harnessDefectNote}

## Actual-game control

${fmt(ctl.games, 0)} games (${fmt(ctl.pairs, 0)} paired) on fresh side-bias-v2 seeds, perspective \`${ctl.perspectiveTeam}\`.

| Measure | Value |
| --- | --- |
| paired win effect | ${fmt(w.delta, 5)} |
| standard deviation | ${fmt(w.sd, 5)} |
| standard error | ${fmt(w.se, 5)} |
| discordant pairs | ${fmt(w.discordantPairs, 0)} |
| 95% Wald interval | [${fmt(w.waldInterval.lower, 5)}, ${fmt(w.waldInterval.upper, 5)}] |
| 95% bootstrap interval | [${fmt(w.bootstrapInterval.lower, 5)}, ${fmt(w.bootstrapInterval.upper, 5)}] |
| z / p | ${fmt(w.z, 4)} / ${fmt(w.p, 4)} |
| score margin effect | ${fmt(ctl.scoreMarginEffect.mean, 4)} (z ${fmt(ctl.scoreMarginEffect.z, 4)}) |
| possession effect | ${fmt(ctl.possessionEffect.mean, 4)} (z ${fmt(ctl.possessionEffect.z, 4)}) |
| overtime effect | ${fmt(ctl.overtimeEffect.mean, 5)} |
| max action-share difference | ${fmt(ctl.actionMix.maxAbsShareDifference, 5)} |
| zone possessions gold / blue | ${fmt(ctl.zoneUsage.goldPossessions, 0)} / ${fmt(ctl.zoneUsage.bluePossessions, 0)} |
| invariant violations | ${fmt(ctl.invariantViolations, 0)} |
| ties | ${fmt(ctl.ties, 0)} |

**Equivalent within the practical margin: ${d.actualGameControlEquivalent}.**

## Adjacent controls

| Control | Teams | Era | Pairs | delta | 95% CI | p |
| --- | --- | --- | --- | --- | --- | --- |
${adj}

${d.adjacentControlsNote}

## Roster-order independence

| Measure | Value |
| --- | --- |
| pairs | ${fmt(d.rosterOrderIndependence.pairs, 0)} |
| teamIntelligence byte-identical | **${d.rosterOrderIndependence.teamIntelligenceByteIdentical}** |
| individual results differing | ${fmt(d.rosterOrderIndependence.differingIndividualResults, 0)} |
| paired win-rate difference | ${fmt(d.rosterOrderIndependence.pairedWinRateDifference, 5)} |
| 95% interval | [${fmt(d.rosterOrderIndependence.waldInterval.lower, 5)}, ${fmt(d.rosterOrderIndependence.waldInterval.upper, 5)}] |
| distribution equivalent within margin | **${d.rosterOrderIndependence.distributionEquivalentWithinMargin}** |
| finding | \`${d.rosterOrderIndependence.finding}\` |

${d.rosterOrderIndependence.explanation}

## Classification

**\`${d.classification}\`** — blocks lock: **${d.blocksLock}**.

${d.reason}
`);
}

// ── side-bias validation v2 ─────────────────────────────────────────────────
{
  const A = R("probability-side-bias-validation-v2"); const d = A.data;
  const cellRows = d.cells.map((c) => {
    const f = c.stages[c.stages.length - 1];
    return `| \`${c.id}\` | ${c.kind} | ${c.era} | ${fmt(c.stageReached, 0)} | ${fmt(c.finalPairs, 0)} | ${fmt(f.delta, 5)} | [${fmt(f.simultaneousWald.lower, 5)}, ${fmt(f.simultaneousWald.upper, 5)}] | [${fmt(f.simultaneousBootstrap.lower, 5)}, ${fmt(f.simultaneousBootstrap.upper, 5)}] | ${fmt(f.holmAdjustedTostP, 4)} | **${c.finalClassification}** |`;
  }).join("\n");
  const stratumTable = (name, g) => `### ${name}\n\n| Stratum | Cells | mean delta | interval | within aggregate margin | systematic |\n| --- | --- | --- | --- | --- | --- |\n` +
    Object.entries(g).map(([k, v]) => `| ${k} | ${fmt(v.cells, 0)} | ${fmt(v.meanDelta, 5)} | [${fmt(v.interval.lower, 5)}, ${fmt(v.interval.upper, 5)}] | ${v.withinAggregateMargin} | ${v.sameDirectionSystematic} |`).join("\n");
  write("probability-side-bias-validation-v2.md", `${provenance(A)}# Probability side-bias validation v2

- policy hash: \`${d.policyHash}\`
- policy frozen before this run: **${d.policyFrozenBeforeThisRun}**
- cells: **${fmt(d.familySize, 0)}**
- games simulated: **${fmt(d.totalGamesSimulated, 0)}**
- simultaneous alpha: ${fmt(d.simultaneousAlpha, 5)}
- per-cell margin: +/-${fmt(d.perCellMargin, 3)} · aggregate margin: +/-${fmt(d.aggregateMargin, 3)}

${countsTable(d.classificationCounts, { header: "Classification" })}

Reconciles: **${d.reconciliation.reconciles}**.

## Gates

| Gate | Verdict |
| --- | --- |
${Object.entries(d.gates).map(([k, v]) => `| \`${k}\` | ${v ? "PASS" : "**FAIL**"} |`).join("\n")}

**SIDE-BIAS GATE v2: ${d.gatePasses ? "PASS" : "FAIL"}.**

## Aggregate

| Measure | Value |
| --- | --- |
| pooled pairs | ${fmt(d.aggregate.pooledPairs, 0)} |
| pooled delta | ${fmt(d.aggregate.pooledDelta, 5)} |
| pooled standard error | ${fmt(d.aggregate.pooledSe, 5)} |
| pooled 95% Wald | [${fmt(d.aggregate.pooledWald.lower, 5)}, ${fmt(d.aggregate.pooledWald.upper, 5)}] |
| pooled 95% bootstrap | [${fmt(d.aggregate.pooledBootstrap.lower, 5)}, ${fmt(d.aggregate.pooledBootstrap.upper, 5)}] |
| mean across cells | ${fmt(d.aggregate.meanAcrossCells, 5)} |
| across-cells interval | [${fmt(d.aggregate.acrossCellsInterval.lower, 5)}, ${fmt(d.aggregate.acrossCellsInterval.upper, 5)}] |
| within aggregate margin | **${d.aggregate.withinAggregateMargin}** |
| invariant violations | ${fmt(d.invariantViolations, 0)} |
| ties | ${fmt(d.ties, 0)} |

## Strata

Systematic strata: **${d.systematicStrata.length ? d.systematicStrata.join(", ") : "none"}**.

${stratumTable("By era", d.strata.byEra)}

${stratumTable("By kind", d.strata.byKind)}

${stratumTable("By coach", d.strata.byCoach)}

## Every cell

| Cell | Kind | Era | Stage | Pairs | delta | simultaneous Wald | simultaneous bootstrap | Holm TOST p | Result |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${cellRows}
`);
}

// ── objective visibility ────────────────────────────────────────────────────
{
  const A = R("objective-visibility-resolution"); const d = A.data;
  const rows = d.resolved.map((r) => `| \`${r.id}\` | ${r.module} | \`${r.mechanic}\` | ${fmt(r.activatedPossessions, 0)} | ${fmt(r.primaryObjectiveVisibility.cellsDiffering, 0)}/${fmt(r.primaryObjectiveVisibility.cellsTotal, 0)} | ${r.conditionalMechanicalTarget.directionConfirmed} | ${fmt(r.defaultValue, 4)} | ${fmt(r.candidateValue, 4)} | \`${r.finalLockClassification}\` |`).join("\n");
  const detail = d.resolved.map((r) => {
    const t = r.conditionalMechanicalTarget;
    const m = (x) => x ? `${fmt(x.atMinMeanDelta, 5)} (t ${fmt(x.atMinT, 4)}) -> ${fmt(x.atMaxMeanDelta, 5)} (t ${fmt(x.atMaxT, 4)})` : "n/a";
    return `### \`${r.id}\`

- claim: ${t.claim}
- mechanic: \`${r.mechanic}\` — ${r.mechanicContext ?? "n/a"}
- activated possessions: ${fmt(r.activatedPossessions, 0)}
- primary objective: **blind** (${fmt(r.primaryObjectiveVisibility.cellsDiffering, 0)}/${fmt(r.primaryObjectiveVisibility.cellsTotal, 0)} cells differ, measured at ${r.primaryObjectiveVisibility.measuredAt})
- ${t.directionMetric}: ${m(t.primary)}
${t.secondaryMetric ? `- ${t.secondaryMetric}: ${m(t.secondary)}` : ""}
- guardrail breaches: ${t.guardrailBreaches.length ? t.guardrailBreaches.join(", ") : "none"}
- direction confirmed: **${t.directionConfirmed}** · mechanically consistent: **${t.mechanicallyConsistent}**
- prior readiness: \`${r.priorReadinessV3}\` -> final: \`${r.finalLockClassification}\`

${r.reclassificationReason}

**What this establishes.** ${t.whatThisEstablishes}

**What it does not.** ${t.whatThisDoesNotEstablish}`;
  }).join("\n\n");
  write("objective-visibility-resolution.md", `${provenance(A)}# Objective-visibility resolution

Parameters read from \`${d.sourceOfParameterIds}\`.

- unseen by the primary objective: **${fmt(d.counts.unseenByPrimaryObjective, 0)}**
- direction confirmed: **${fmt(d.counts.directionConfirmed, 0)}**
- mechanically consistent: **${fmt(d.counts.mechanicallyConsistent, 0)}**
- frozen at default: **${fmt(d.counts.frozenAtDefault, 0)}**
- parameter search performed: **${d.noParameterSearchPerformed ? "no" : "YES"}**

${d.noParameterSearchNote}

## Classes

${d.visibilityClasses.map((c) => `- \`${c}\``).join("\n")}

## Summary

| Parameter | Module | Mechanic | Activated | Objective cells differing | Direction confirmed | Default | Candidate | Final class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows}

${detail}

## Readiness v4

${countsTable(d.readinessV4, { header: "Readiness class" })}

Reconciles: **${d.readinessReconciliation.reconciles}** against ${fmt(d.activeParameterCount, 0)} active parameters.

All values at registry default: **${d.allValuesAtRegistryDefault}**.
`);
}

// ── baseline candidate lock ─────────────────────────────────────────────────
{
  const A = R("baseline-candidate-lock"); const d = A.data;
  const gateRows = d.engineeringGates.map((g) => `| \`${g.name}\` | ${g.pass ? "PASS" : "**FAIL**"} | ${g.detail} |`).join("\n");
  write("baseline-candidate-lock.md", `${provenance(A)}# Baseline candidate lock

| Field | Value |
| --- | --- |
| \`candidateId\` | ${d.candidateId} |
| \`candidateSelectionStatus\` | **${d.candidateSelectionStatus}** |
| \`candidateLockStatus\` | **${d.candidateLockStatus}** |
| \`calibrationStatus\` | **${d.calibrationStatus}** |
| \`possessionCalibrationVersion\` | **${d.possessionCalibrationVersion}** |
| \`parameterChanges\` | ${fmt(d.parameterChanges, 0)} |
| \`parameterSetHash\` | \`${d.parameterSetHash}\` |
| \`parameterSetStatus\` | \`${d.parameterSetStatus}\` |
| \`registryDefaultsHash\` | \`${d.registryDefaultsHash}\` |
| active parameters | ${fmt(d.activeParameterCount, 0)} |
| \`manifestHash\` | \`${d.manifestHash}\` |
| \`creationCommit\` | \`${d.creationCommit}\` |
| lock blockers | ${d.candidateLockBlockers.length ? d.candidateLockBlockers.join(", ") : "(none)"} |

## What this lock means

${d.scopeOfLock.means.map((x) => `- ${x}`).join("\n")}

## What it does not mean

${d.scopeOfLock.doesNotMean.map((x) => `- ${x}`).join("\n")}

## Engineering gates

${fmt(d.engineeringGates.filter((g) => g.pass).length, 0)} of ${fmt(d.engineeringGates.length, 0)} pass. All pass: **${d.allEngineeringGatesPass}**.

| Gate | Verdict | Detail |
| --- | --- | --- |
${gateRows}

## Content-addressed inputs

| Input | Hash |
| --- | --- |
| candidate history | \`${d.candidateHistoryHash}\` |
| candidate search policy | \`${d.candidateSearchPolicyHash}\` |
| candidate comparison | \`${d.candidateComparisonHash}\` |
| candidate status reconciliation | \`${d.candidateStatusReconciliationHash}\` |
| side-bias policy v2 | \`${d.probabilitySideBiasPolicyHash}\` |
| side-bias seed set | \`${d.probabilitySideBiasSeedSetHash}\` |
| side-bias validation v2 | \`${d.probabilitySideBiasValidationHash}\` |
| prior failing cell | \`${d.priorFailingCellHash}\` |
| orientation audit | \`${d.orientationAuditHash}\` |
| probability validation | \`${d.probabilityValidationHash}\` |
| side symmetry | \`${d.sideSymmetryValidationHash}\` |
| internal validation | \`${d.internalValidationHash}\` |
| readiness | \`${d.readinessHash}\` |
| objective visibility | \`${d.objectiveVisibilityResolutionHash}\` |
| targeted fixture coverage | \`${d.targetedFixtureCoverageHash}\` |
| superseded v1 gate artifact | \`${d.supersededV1GateArtifactHash}\` |

## Engine and data versions

${Object.entries(d.engineVersions).map(([k, v]) => `- \`${k}\`: ${v}`).join("\n")}

${Object.entries(d.dataVersions).map(([k, v]) => `- \`${k}\`: ${v}`).join("\n")}

## Formal holdouts

| Holdout | State | Access count | Manifest hash |
| --- | --- | --- | --- |
| historical holdout v3 | ${d.formalHoldoutState.historicalHoldoutV3} | ${fmt(d.formalHoldoutAccessCounts.historicalHoldoutV3, 0)} | \`${d.formalHoldoutHashes.historicalHoldoutV3}\` |
| synthetic stress holdout v2 | ${d.formalHoldoutState.syntheticStressHoldoutV2} | ${fmt(d.formalHoldoutAccessCounts.syntheticStressHoldoutV2, 0)} | \`${d.formalHoldoutHashes.syntheticStressHoldoutV2}\` |

## Unadjudicated frozen parameters

| Parameter | Default | Class | Mechanically consistent |
| --- | --- | --- | --- |
${d.unadjudicatedFrozenParameters.map((p) => `| \`${p.id}\` | ${fmt(p.defaultValue, 4)} | \`${p.finalLockClassification}\` | ${p.mechanicallyConsistent} |`).join("\n")}

## Readiness

${countsTable(d.readinessV4, { header: "Readiness class" })}

## Post-lock mutation policy

${d.postLockMutationPolicy}
`);
}

// ── phase 6C3 package ──────────────────────────────────────────────────────
{
  const A = R("phase-6c3-validation-package"); const d = A.data;
  write("phase-6c3-validation-package.md", `${provenance(A)}# Phase 6C3 validation package — ${d.state}

**Nothing here has been run.** Holdout commands executed: **${fmt(d.holdoutCommandsExecuted, 0)}**.

## Locked candidate

| Field | Value |
| --- | --- |
${Object.entries(d.lockedCandidate).map(([k, v]) => `| \`${k}\` | \`${v}\` |`).join("\n")}

## Preconditions

**${fmt(d.preconditionsMet, 0)} of ${fmt(d.preconditions.length, 0)} met. Ready to run: ${d.readyToRun}.**

| Precondition | Met | Detail |
| --- | --- | --- |
${d.preconditions.map((p) => `| ${p.name} | ${p.met ? "yes" : "**NO**"} | ${p.detail} |`).join("\n")}

${d.readinessNote}

## Holdouts

| Holdout | Members | State | Access count | Manifest hash |
| --- | --- | --- | --- | --- |
| historical holdout v3 | ${fmt(d.holdouts.historicalHoldoutV3.members, 0)} | ${d.holdouts.historicalHoldoutV3.state} | ${fmt(d.holdouts.historicalHoldoutV3.comparisonAccessCount, 0)} | \`${d.holdouts.historicalHoldoutV3.manifestHash}\` |
| synthetic stress holdout v2 | ${fmt(d.holdouts.syntheticStressHoldoutV2.members, 0)} | ${d.holdouts.syntheticStressHoldoutV2.state} | ${fmt(d.holdouts.syntheticStressHoldoutV2.comparisonAccessCount, 0)} | \`${d.holdouts.syntheticStressHoldoutV2.manifestHash}\` |

## Commands prepared

| Command | Opens a holdout | Executed |
| --- | --- | --- |
${d.commandsPrepared.map((c) => `| \`${c.command}\` | ${c.opensHoldout} | ${fmt(c.executed, 0)} |`).join("\n")}

## Replay commands

${d.replayCommands.map((c) => `- \`${c}\``).join("\n")}

## Expected runtime

${Object.entries(d.expectedRuntime).map(([k, v]) => `- ${k}: ${v}`).join("\n")}

## Execution order

${d.executionOrder.map((x, i) => `${i + 1}. ${x}`).join("\n")}

## Failure behaviour

${Object.entries(d.failureBehaviour).map(([k, v]) => `- **${k}**: ${v}`).join("\n")}

## Private-preview prerequisites

${d.privatePreviewPrerequisites.map((x) => `- ${x}`).join("\n")}

## Not claimed

${d.notClaimed.map((x) => `- ${x}`).join("\n")}

- package hash: \`${d.packageHash}\`
`);
}

console.log(`RENDERED ${written.length} document(s)`);
for (const p of written) console.log(`  ${p}`);
console.log(`\nrenderer version ${versionOf("calibrationReportRendererVersion")} — formats only, never computes`);
}
