import { T, card } from '../theme.js';
const policyLink = { color: T.blue, display: 'inline-flex', alignItems: 'center', minHeight: 44, padding: '0 6px' };
export const LAST_UPDATED = '10-02-2026';
export function PolicyPage({ kind }) {
  const privacy = kind === 'privacy';
  return <main style={{ maxWidth: 800, margin: '24px auto', padding: 20 }}><article style={{ ...card, padding: 24 }}>
    <h1>{privacy ? 'Privacy' : 'Terms of play'}</h1><p>Last updated {LAST_UPDATED}</p>
    {privacy ? <><p>Guest play uses a first-party session cookie and local browser storage for draft continuity, completed games, and Daily attempt reminders. Clearing browser storage removes that device history and can reset guest identity.</p><p>If accounts are enabled, Supabase handles email sign-in and stores your private profile, saved games, rosters, preferences, progression and Challenge records. Public profiles and leaderboards use their visibility controls; your email is not a public display name.</p><p>Sharing a public result card publishes its matchup, score, selected player names and recap to anyone with the link. Governed Challenge invitations keep the draft hidden until the recipient finishes. Room invitations give recipients access to that room.</p><p>Named gameplay and sharing events use a pseudonymous browser identifier. The existing event store retains raw logs for 14 days. Optional Vercel Analytics or PostHog adapters activate only when configured; third-party delivery is currently unverified. Events exclude email, passwords, auth tokens and free-text player input.</p><p>Email codes are sent by the account provider when configured. Room email notifications are disabled. Account export and deletion controls are available in My EraClash when accounts are enabled.</p><p>Data-controller identity, retention beyond the existing event-log policy, and a privacy contact remain owner release decisions. This page describes the implemented code; it does not certify a live provider configuration.</p></> : <><p>EraClash is an independent basketball simulation for entertainment. Results describe a game model, not a promise about real athletes or future games. Guest play is available without payment; an account is offered to save progress.</p><p>Use your own account and do not impersonate others, exploit APIs, submit abusive material or interfere with other players. A shared recap is public; share only a result you intend to disclose.</p><p>EraClash is not affiliated with, endorsed by, or sponsored by any professional basketball league or team. Player names and historical references are descriptive; neutral copy does not establish rights clearance.</p><p>Optional Founding Player support does not change odds, player capability, rankings, or access to play. Any payment is handled by the configured external provider under that provider’s terms.</p><p>The owner must confirm the operator’s legal identity, contact, governing terms, age policy and commercial rights before public release. These implementation terms require owner review.</p></>}
    <p><a href="/clash/modes" style={policyLink}>Play a mode</a> · <a href={privacy ? '/terms' : '/privacy'} style={policyLink}>{privacy ? 'Terms' : 'Privacy'}</a></p>
  </article></main>;
}
export function SupportPage() {
  const raw = import.meta.env?.STRIPE_PAYMENT_LINK || import.meta.env?.VITE_STRIPE_PAYMENT_LINK || '';
  const paymentLink = /^https:\/\/buy\.stripe\.com\/[A-Za-z0-9_/-]+$/.test(raw) ? raw : null;
  return <main style={{ maxWidth: 800, margin: '24px auto', padding: 20 }}><article style={{ ...card, padding: 24 }}><h1>Founding Player</h1><p>Help sustain independent basketball simulations. Support never changes the game, rankings, or access to play.</p>{paymentLink ? <a href={paymentLink} rel="noopener noreferrer" style={{ display: 'inline-block', minHeight: 44, padding: '12px 20px', background: T.gold, color: T.onGold, borderRadius: 8 }}>Support EraClash</a> : null}<p><a href="/clash/modes" style={policyLink}>Keep playing</a> · <a href="/privacy" style={policyLink}>Privacy</a> · <a href="/terms" style={policyLink}>Terms</a></p></article></main>;
}
