import { useState } from 'react';
import { loopApi } from './client.js';
import { T, card } from '../theme.js';
import { loopEvent } from './events.js';
const control = { minHeight: 44, padding: '12px 18px', borderRadius: 8, border: `1px solid ${T.goldBorder}`, background: T.bgCard, color: T.text, font: 'inherit', cursor: 'pointer' };
export default function PrivateRooms({ signedIn = false }) {
  const [room, setRoom] = useState(null), [invite, setInvite] = useState(() => new URLSearchParams(location.search).get('invite') || ''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [copied, setCopied] = useState(false);
  const [challengeCode, setChallengeCode] = useState('');
  const act = async op => { setBusy(true); setError(''); try { const out = await loopApi({ op, roomId: invite, ...(op === 'room-share-challenge' ? { challengeCode } : {}) }); setRoom(out.room); setInvite(out.roomId); loopEvent('mode_started', { mode: 'rooms' }); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <main style={{ maxWidth: 900, margin: '24px auto', padding: 20 }}><section style={{ ...card, padding: 24 }}><h1>Private rooms</h1><p>Invite a group, post your own completed Clashes, and compare their results. Anyone receiving an invitation can join. Email notifications are disabled.</p>
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}><button style={control} disabled={busy} onClick={() => act('room-create')}>Create a room</button><label>Invitation code<input value={invite} onChange={e => setInvite(e.target.value.trim())} style={{ ...control, display: 'block', maxWidth: '100%', boxSizing: 'border-box' }} /></label><button style={control} disabled={busy || !invite} onClick={() => act('room-join')}>Join invitation</button></div>
    {error ? <p role="alert">{error}</p> : null}
    {room ? <><h2>Your room · {room.memberCount} members</h2><button style={control} onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/clash/rooms?invite=${room.id}`); setCopied(true); } catch { setCopied(false); setError('Copy is unavailable. Select the invitation address below and copy it manually.'); } }}>{copied ? 'Invitation copied' : 'Copy invitation'}</button> <a href={`/clash/any-five?room=${room.id}`} style={{ ...control, display: 'inline-block', textDecoration: 'none' }}>Play for this room</a><p><label>Invitation address<input readOnly value={`${location.origin}/clash/rooms?invite=${room.id}`} style={{ ...control, display: 'block', width: '100%', boxSizing: 'border-box' }} onFocus={e => e.target.select()} /></label></p><h3>Room leaderboard</h3>{room.entries.length ? <ol>{room.entries.map(entry => <li key={entry.resultId}>{entry.path ? <a href={entry.path} style={{ ...control, display: 'inline-flex' }}>{entry.score.gold}–{entry.score.blue} · margin {entry.margin}</a> : <span>{entry.score.gold}–{entry.score.blue} · margin {entry.margin}</span>}</li>)}</ol> : <p>No completed games yet. Play a Clash to start the board.</p>}<h3>Room Challenge feed</h3><p>Completed result cards and your live governed Challenge invitations.</p><label>Governed Challenge code<input style={{ ...control, display: 'block', maxWidth: '100%' }} value={challengeCode} onChange={e => setChallengeCode(e.target.value)} /></label><button style={control} disabled={busy || !signedIn || !challengeCode} onClick={() => act('room-share-challenge')}>Share my Challenge</button>{!signedIn ? <p>Sign in to share a governed Challenge you created. Guests can play and compare room results.</p> : null}{room.feed.length ? <ul>{room.feed.map(entry => <li key={entry.resultId}>{entry.path ? <a href={entry.path} style={{ ...control, display: 'inline-flex' }}>{entry.kind === 'governed-challenge' ? 'Play this governed Challenge' : 'Open completed Clash'}</a> : 'Completed Clash'} · {new Date(entry.createdAt).toLocaleDateString('en-US')}</li>)}</ul> : <p>Completed games shared to this room appear here.</p>}<button style={control} disabled={busy} onClick={() => act('room-read')}>Refresh room</button></> : null}
    <p><a href="/clash/modes" style={{ ...control, display: 'inline-flex', alignItems: 'center' }}>All modes</a> · <a href="/privacy" style={{ ...control, display: 'inline-flex', alignItems: 'center' }}>Privacy</a> · <a href="/terms" style={{ ...control, display: 'inline-flex', alignItems: 'center' }}>Terms</a></p>
  </section></main>;
}
