// ── The ONE resolver: three token layers → one scoped stylesheet ─────────────
// Every theme renders from the same DOM. Theme selection sets data-theme on the
// document element; the generated stylesheet (src/theme/basketball-themes.css,
// written by scripts/ui/build-theme-css.mjs from this module) supplies the
// variables under that attribute. Without data-theme nothing here applies and
// the product renders exactly as it did before Phase 9A.1.
//
// Two scopes per theme:
//   html[data-theme="x"]                 → --ec-t-* (reading), root aliases, --ec-l-* (lobby)
//   [data-theme="x"] .ec-arena-shell     → --ec-a-* (arena), which index.css declares on the shell
import { BASKETBALL_THEMES, themeRootAliases } from "./basketballThemes.js";
import { THEME_IDS, ARENA_KEYS, LOBBY_KEYS, READING_KEYS, ROOT_ALIAS_KEYS, CONTROL_THEME_ID } from "./themeTypes.js";
import { MASTER_BRAND_VERSION } from "./masterBrandTokens.js";
import { SEMANTIC_VERSION } from "./semanticTokens.js";

export const THEME_RESOLVER_VERSION = "1.0.0";
export { THEME_IDS, CONTROL_THEME_ID };

export const getTheme = (id) => BASKETBALL_THEMES[id] || null;
export const isThemeId = (id) => THEME_IDS.includes(String(id));

/** Every key present, no extras: a theme that forgets a token is a build error. */
export const validateTheme = (theme) => {
  const problems = [];
  const check = (obj, keys, scope) => {
    for (const k of keys) if (!(k in obj)) problems.push(`${theme.id}: missing ${scope} token "${k}"`);
    for (const k of Object.keys(obj)) if (!keys.includes(k)) problems.push(`${theme.id}: unknown ${scope} token "${k}"`);
  };
  check(theme.arena, ARENA_KEYS, "arena");
  check(theme.lobby, LOBBY_KEYS, "lobby");
  check(theme.reading, READING_KEYS, "reading");
  const aliases = themeRootAliases(theme);
  check(aliases, ROOT_ALIAS_KEYS, "root-alias");
  for (const k of ["teamGold", "teamBlue", "coachViolet", "success", "danger"]) if (!theme.semantic?.[k]) problems.push(`${theme.id}: missing semantic ${k}`);
  return problems;
};

const decl = (prefix, obj) => Object.entries(obj).map(([k, v]) => `  ${prefix}${k}: ${v};`).join("\n");

/** The CSS for one theme. */
export const themeCssFor = (id) => {
  const t = getTheme(id);
  if (!t) throw new Error(`unknown theme ${id}`);
  const problems = validateTheme(t);
  if (problems.length) throw new Error(problems.join("\n"));
  return [
    `/* ── ${t.label} (${t.role}) ─────────────────────────────────── */`,
    `html[data-theme="${id}"] {`,
    decl("--ec-t-", t.reading),
    decl("--", themeRootAliases(t)),
    decl("--ec-l-", t.lobby),
    `  color-scheme: ${t.secondaryIsLight || id === "modern-court" ? "light" : "dark"};`,
    `}`,
    `html[data-theme="${id}"] .ec-arena-shell {`,
    decl("--ec-a-", t.arena),
    `}`,
  ].join("\n");
};

/** The whole stylesheet: a header, then every theme in THEME_IDS order. */
export const themeCss = () => [
  `/* GENERATED by scripts/ui/build-theme-css.mjs from src/theme/basketballThemes.js — do not edit by hand.`,
  `   master brand ${MASTER_BRAND_VERSION} · semantic ${SEMANTIC_VERSION} · resolver ${THEME_RESOLVER_VERSION}`,
  `   Applies only under html[data-theme]; the default product is untouched. */`,
  ...THEME_IDS.map(themeCssFor),
  "",
].join("\n");

/** Apply a theme to the document (the lab and the screenshot harness only). */
export const applyTheme = (id, root = typeof document !== "undefined" ? document.documentElement : null) => {
  if (!root) return false;
  if (!id) { delete root.dataset.theme; return true; }
  if (!isThemeId(id)) return false;
  root.dataset.theme = id;
  return true;
};

/** A flat, auditable token table for a theme — what the artifacts record. */
export const themeTokenTable = (id) => {
  const t = getTheme(id);
  return {
    id, label: t.label, role: t.role, character: t.character, families: t.families, semantic: t.semantic,
    tokens: {
      arena: Object.fromEntries(Object.entries(t.arena).map(([k, v]) => [`--ec-a-${k}`, v])),
      lobby: Object.fromEntries(Object.entries(t.lobby).map(([k, v]) => [`--ec-l-${k}`, v])),
      reading: Object.fromEntries(Object.entries(t.reading).map(([k, v]) => [`--ec-t-${k}`, v])),
      rootAliases: Object.fromEntries(Object.entries(themeRootAliases(t)).map(([k, v]) => [`--${k}`, v])),
    },
  };
};
