#!/usr/bin/env node
// ── Render Phase 6C4A documents from artifacts ──────────────────────────────
//   npm run c1:report
// Formats only. Never sums, counts, averages or derives. Renders whichever
// 6C4A artifacts exist, so it can run after every workstream.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt } from "../../src/v3/calibration/artifacts.js";
import { DIR } from "./failureRegister.mjs";

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const has = (n) => artifactExists(n, DIR);
const R = (n) => readArtifact(n, DIR);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run c1:report  from: ${a.generationCommand} -->\n`;

if (import.meta.url === `file://${process.argv[1]}`) {
  if (has("historical-v4-failure-register")) {
    const A = R("historical-v4-failure-register"); const d = A.data;
    write("historical-v4-failure-register.md", `${prov(A)}# Historical Holdout V4 — failure register

Every hard failure from the formal V4 run, read directly from
\`historical-holdout-v4-results.json\` (never from prose), classified exactly once.
The set is a consumed \`FAILED_HOLDOUT_DIAGNOSTIC_SET\`: usable for development,
never rescored, never a fresh holdout.

- hard failures in the verdict: **${d.hardFailuresInVerdict}**
- failures registered: **${d.failuresRegistered}** (reconciles: **${d.reconciles}**)
- substantive (engine change required): **${d.substantiveCount}**
- practical-margin-only (engine change prohibited): **${d.byCategory.PRACTICAL_MARGIN_ONLY}**

| category | count |
| --- | ---: |
${Object.entries(d.byCategory).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

## Register

| id | team-season | trait | metric | diff | z | category |
| --- | --- | --- | --- | ---: | ---: | --- |
${d.failures.map((f) => `| \`${f.failureId}\` | ${f.teamSeason} | \`${f.traitId}\` | \`${f.metricId}\` | ${fmt(f.difference)} | ${fmt(f.z)} | \`${f.category}\` |`).join("\n")}

## Practical-margin-only artifacts

These four failed the frozen V4 rule (sign + CI excluding zero, no practical
margin). Their magnitudes fall below any justifiable practical margin, so the
correct repair is to the validation policy — prospectively — not to the engine.

| id | trait | team-season | diff | engine change | policy change |
| --- | --- | --- | ---: | --- | --- |
${d.marginArtifacts.map((m) => `| \`${m.failureId}\` | \`${m.traitId}\` | ${m.teamSeason} | ${fmt(m.difference)} | **${m.ENGINE_CHANGE_REQUIRED}** | **${m.POLICY_V3_CHANGE_REQUIRED}** |`).join("\n")}

## Substantive failures — repair scaffolding

| id | team-season | metric | suspected mechanic | acceptance |
| --- | --- | --- | --- | --- |
${d.registerDetail.map((f) => `| \`${f.failureId}\` | ${f.teamSeason} | \`${f.metricId}\` | ${f.suspectedMechanic} | ${f.candidateAcceptanceCriteria} |`).join("\n")}

Every substantive failure's mechanic chain: \`trait → source inputs → player
intelligence → team intelligence → coach deployment → raw action weights →
normalized weights → reachability → conditional outcomes → game metric\`.
No engine change before root-cause evidence exists.`);
  }

  if (has("candidate0-preservation")) {
    const A = R("candidate0-preservation"); const d = A.data;
    write("candidate0-preservation.md", `${prov(A)}# Candidate 0 preservation — Phase 6C4A

Candidate 1 is a **separate candidate**. Candidate 0 is never mutated; it
replays exactly from the commit recorded here.

| fact | value |
| --- | --- |
| candidate | \`${d.candidate0.candidateId}\` — SELECTED / LOCKED |
| core hash | \`${d.candidate0.coreHash}\` |
| parameter set hash | \`${d.candidate0.parameterSetHash}\` |
| possessionCalibrationVersion | \`${d.candidate0.possessionCalibrationVersion}\` |
| behaviour snapshot | \`${d.candidate0.behaviourSnapshotHash}\` |
| production engine source sha256 | \`${d.candidate0.productionEngineSha256}\` |
| git commit before Candidate 1 | \`${d.candidate0.gitCommitBeforeCandidate1}\` |

${d.candidate0.replayGuarantee}.

| preserved verdict | status | access count |
| --- | --- | ---: |
| Historical V3 | \`${d.historicalV3.verdict}\` | ${d.historicalV3.accessCount} |
| Historical V4 | \`${d.historicalV4.verdict}\` → \`${d.historicalV4.setStatus}\` | ${d.historicalV4.accessCount} |
| Synthetic V2 | \`${d.syntheticV2.status}\` | ${d.syntheticV2.accessCount} |`);
  }

  if (has("target-schema-validation")) {
    const A = R("target-schema-validation"); const d = A.data;
    const B = has("profile-resolution-audit") ? R("profile-resolution-audit") : null;
    const C = has("runner-preflight-audit") ? R("runner-preflight-audit") : null;
    write("validation-instrumentation-repairs.md", `${prov(A)}# Validation instrumentation repairs — Phase 6C4A

Three instrumentation defects from 6C3R, repaired at the shared-module level
and proven against the real stores.

## 1. Typed target access (\`readTargetValue\`)

${d.defectRepaired}.

| census | count |
| --- | ---: |
| target entries | ${d.census.entriesTotal} |
| usable under the typed accessor | **${d.census.typedUsable}** |
| "available" under object truthiness | ${d.census.naiveAvailable} |
| truthiness over-report | **${d.truthinessOverreport}** |
| schema violations | ${d.schemaViolations} |

Value-bearing statuses: ${d.valueBearingStatuses.map((x) => `\`${x}\``).join(", ")}. Everything else is
typed as unusable — object truthiness is not evidence.
${B ? `
## 2. Exact profile resolution

| fact | value |
| --- | ---: |
| combined profiles (v3 + v4) | ${B.data.combinedProfiles} |
| unresolved | ${B.data.unresolved} |
| duplicate ids | ${B.data.duplicateIds} |
| last-name collisions (distinct persons sharing a surname) | ${B.data.lastNameCollisions} |
| alias titles (exact, recorded) | ${B.data.aliasTitles.length} |
| bare-surname resolutions | **${B.data.bareSurnameResolutions.length}** |

${B.data.rule}` : ""}
${C ? `
## 3. Runner preflight on the exact profile map

${C.data.defectRepaired}

${C.data.rule}

| preflight | result |
| --- | ---: |
| required profile ids (fixtures + era-reference fives) | ${C.data.exactMap.required} |
| resolved through \`buildRunnerProfileMap()\` | ${C.data.exactMap.resolved} |
| the simplified V4-only map would have missed | **${C.data.simplifiedMapWouldHaveMissed}** |` : ""}`);
  }

  if (has("trait-practical-margin-policy")) {
    const A = R("trait-practical-margin-policy"); const d = A.data;
    write("trait-practical-margin-policy.md", `${prov(A)}# Trait practical-margin policy (prospective)

**Frozen. policyHash \`${d.policyHash}\`. Applies from ${d.appliesFrom}.**
${d.neverAppliesTo}.

A trait hard-fails only when **both** hold:

- **statistical** — wrong direction and the 95% CI excludes zero (the V4 rule), and
- **practical** — |difference| exceeds the metric's margin below.

Wrong-direction results inside the margin are \`DIRECTIONAL_SOFT_FAIL\`s: reported, never verdict-driving.

| metric | margin | unit | binding | 8×SE at n=${d.rule.protocolGamesPerSurface} | basis |
| --- | ---: | --- | --- | ---: | --- |
${Object.entries(d.metrics).map(([m, v]) => `| \`${m}\` | ${v.margin} | ${v.unit} | ${v.binding} | ${v.noiseComponent ?? "n/a"} | ${v.basis} |`).join("\n")}

Noise basis: ${d.noiseBasis}.`);
  }

  if (has("candidate1-root-cause-analysis")) {
    const A = R("candidate1-root-cause-analysis"); const d = A.data;
    write("candidate1-root-cause-analysis.md", `${prov(A)}# Candidate 1 — root-cause analysis of the V4 substantive failures

No engine change before root-cause evidence exists. This document is that
evidence: ${d.rootCaused}/${d.substantiveFailures} substantive failures walked through the complete mechanic
chain, with factorial intervention cells (${d.gamesPerCell} games each, diagnostic seed
master \`${d.seedMaster}\`). Interventions are \`DIAGNOSTIC_ONLY\` profile clones —
never data, never a repair.

## Root-cause classes

| class | failures |
| --- | --- |
${Object.entries(d.rootCauseClasses).map(([k, v]) => `| \`${k}\` | ${v.join(", ")} |`).join("\n")}

## Dead team-intelligence channels (shared structural evidence)

Channels whose value is (near-)constant across every V4 fixture AND every era
reference — carrying no identity at all for calibration-built teams:

| channel | distinct values | dead |
| --- | --- | --- |
${Object.entries(d.deadTeamIntelligenceChannels).map(([k, v]) => `| \`${k}\` | ${v.distinctValues.slice(0, 6).join(", ")} | **${v.dead}** |`).join("\n")}

## Per-failure conclusions

${Object.values(d.conclusions).map((c) => `### ${c.failureId} — ${c.teamSeason} · \`${c.traitId}\` · \`${c.metricId}\`

**Root cause:** ${c.rootCause}

| chain stage | finding |
| --- | --- |
${Object.entries(c.chain).map(([k, v]) => `| ${k} | ${typeof v === "string" ? v.replace(/\|/g, "\\|") : "see artifact"} |`).join("\n")}

**Factorial cells:**

| cell | ${Object.keys(c.factorial[0]).filter((k) => !["label", "games", "invariantViolations"].includes(k)).join(" | ")} |
| --- | ${Object.keys(c.factorial[0]).filter((k) => !["label", "games", "invariantViolations"].includes(k)).map(() => "---:").join(" | ")} |
${c.factorial.map((f) => `| ${f.label} | ${Object.entries(f).filter(([k]) => !["label", "games", "invariantViolations"].includes(k)).map(([, v]) => v?.mean ?? "—").join(" | ")} |`).join("\n")}

**Repair direction:** ${c.repairDirection}
`).join("\n")}`);
  }

  console.log(written.length ? written.join("\n") : "no 6c4a artifacts yet");
}
