#!/usr/bin/env node
// ── Render Phase 6C4A documents from artifacts ──────────────────────────────
//   npm run c1:report
// Formats only. Never sums, counts, averages or derives. Renders whichever
// 6C4A artifacts exist, so it can run after every workstream.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt } from "../../src/v3/calibration/artifacts.js";
import { DIR } from "./failureRegister.mjs";

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const has = (n) => artifactExists(n, DIR);
const R = (n) => readArtifact(n, DIR);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run c1:report  from: ${a.generationCommand} -->\n`;

if (import.meta.url === `file://${process.argv[1]}`) {
  if (has("historical-v4-failure-register")) {
    const A = R("historical-v4-failure-register"); const d = A.data;
    write("historical-v4-failure-register.md", `${prov(A)}# Historical Holdout V4 — failure register

Every hard failure from the formal V4 run, read directly from
\`historical-holdout-v4-results.json\` (never from prose), classified exactly once.
The set is a consumed \`FAILED_HOLDOUT_DIAGNOSTIC_SET\`: usable for development,
never rescored, never a fresh holdout.

- hard failures in the verdict: **${d.hardFailuresInVerdict}**
- failures registered: **${d.failuresRegistered}** (reconciles: **${d.reconciles}**)
- substantive (engine change required): **${d.substantiveCount}**
- practical-margin-only (engine change prohibited): **${d.byCategory.PRACTICAL_MARGIN_ONLY}**

| category | count |
| --- | ---: |
${Object.entries(d.byCategory).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

## Register

| id | team-season | trait | metric | diff | z | category |
| --- | --- | --- | --- | ---: | ---: | --- |
${d.failures.map((f) => `| \`${f.failureId}\` | ${f.teamSeason} | \`${f.traitId}\` | \`${f.metricId}\` | ${fmt(f.difference)} | ${fmt(f.z)} | \`${f.category}\` |`).join("\n")}

## Practical-margin-only artifacts

These four failed the frozen V4 rule (sign + CI excluding zero, no practical
margin). Their magnitudes fall below any justifiable practical margin, so the
correct repair is to the validation policy — prospectively — not to the engine.

| id | trait | team-season | diff | engine change | policy change |
| --- | --- | --- | ---: | --- | --- |
${d.marginArtifacts.map((m) => `| \`${m.failureId}\` | \`${m.traitId}\` | ${m.teamSeason} | ${fmt(m.difference)} | **${m.ENGINE_CHANGE_REQUIRED}** | **${m.POLICY_V3_CHANGE_REQUIRED}** |`).join("\n")}

## Substantive failures — repair scaffolding

| id | team-season | metric | suspected mechanic | acceptance |
| --- | --- | --- | --- | --- |
${d.registerDetail.map((f) => `| \`${f.failureId}\` | ${f.teamSeason} | \`${f.metricId}\` | ${f.suspectedMechanic} | ${f.candidateAcceptanceCriteria} |`).join("\n")}

Every substantive failure's mechanic chain: \`trait → source inputs → player
intelligence → team intelligence → coach deployment → raw action weights →
normalized weights → reachability → conditional outcomes → game metric\`.
No engine change before root-cause evidence exists.`);
  }

  if (has("candidate0-preservation")) {
    const A = R("candidate0-preservation"); const d = A.data;
    write("candidate0-preservation.md", `${prov(A)}# Candidate 0 preservation — Phase 6C4A

Candidate 1 is a **separate candidate**. Candidate 0 is never mutated; it
replays exactly from the commit recorded here.

| fact | value |
| --- | --- |
| candidate | \`${d.candidate0.candidateId}\` — SELECTED / LOCKED |
| core hash | \`${d.candidate0.coreHash}\` |
| parameter set hash | \`${d.candidate0.parameterSetHash}\` |
| possessionCalibrationVersion | \`${d.candidate0.possessionCalibrationVersion}\` |
| behaviour snapshot | \`${d.candidate0.behaviourSnapshotHash}\` |
| production engine source sha256 | \`${d.candidate0.productionEngineSha256}\` |
| git commit before Candidate 1 | \`${d.candidate0.gitCommitBeforeCandidate1}\` |

${d.candidate0.replayGuarantee}.

| preserved verdict | status | access count |
| --- | --- | ---: |
| Historical V3 | \`${d.historicalV3.verdict}\` | ${d.historicalV3.accessCount} |
| Historical V4 | \`${d.historicalV4.verdict}\` → \`${d.historicalV4.setStatus}\` | ${d.historicalV4.accessCount} |
| Synthetic V2 | \`${d.syntheticV2.status}\` | ${d.syntheticV2.accessCount} |`);
  }

  if (has("target-schema-validation")) {
    const A = R("target-schema-validation"); const d = A.data;
    const B = has("profile-resolution-audit") ? R("profile-resolution-audit") : null;
    const C = has("runner-preflight-audit") ? R("runner-preflight-audit") : null;
    write("validation-instrumentation-repairs.md", `${prov(A)}# Validation instrumentation repairs — Phase 6C4A

Three instrumentation defects from 6C3R, repaired at the shared-module level
and proven against the real stores.

## 1. Typed target access (\`readTargetValue\`)

${d.defectRepaired}.

| census | count |
| --- | ---: |
| target entries | ${d.census.entriesTotal} |
| usable under the typed accessor | **${d.census.typedUsable}** |
| "available" under object truthiness | ${d.census.naiveAvailable} |
| truthiness over-report | **${d.truthinessOverreport}** |
| schema violations | ${d.schemaViolations} |

Value-bearing statuses: ${d.valueBearingStatuses.map((x) => `\`${x}\``).join(", ")}. Everything else is
typed as unusable — object truthiness is not evidence.
${B ? `
## 2. Exact profile resolution

| fact | value |
| --- | ---: |
| combined profiles (v3 + v4) | ${B.data.combinedProfiles} |
| unresolved | ${B.data.unresolved} |
| duplicate ids | ${B.data.duplicateIds} |
| last-name collisions (distinct persons sharing a surname) | ${B.data.lastNameCollisions} |
| alias titles (exact, recorded) | ${B.data.aliasTitles.length} |
| bare-surname resolutions | **${B.data.bareSurnameResolutions.length}** |

${B.data.rule}` : ""}
${C ? `
## 3. Runner preflight on the exact profile map

${C.data.defectRepaired}

${C.data.rule}

| preflight | result |
| --- | ---: |
| required profile ids (fixtures + era-reference fives) | ${C.data.exactMap.required} |
| resolved through \`buildRunnerProfileMap()\` | ${C.data.exactMap.resolved} |
| the simplified V4-only map would have missed | **${C.data.simplifiedMapWouldHaveMissed}** |` : ""}`);
  }

  if (has("trait-practical-margin-policy")) {
    const A = R("trait-practical-margin-policy"); const d = A.data;
    write("trait-practical-margin-policy.md", `${prov(A)}# Trait practical-margin policy (prospective)

**Frozen. policyHash \`${d.policyHash}\`. Applies from ${d.appliesFrom}.**
${d.neverAppliesTo}.

A trait hard-fails only when **both** hold:

- **statistical** — wrong direction and the 95% CI excludes zero (the V4 rule), and
- **practical** — |difference| exceeds the metric's margin below.

Wrong-direction results inside the margin are \`DIRECTIONAL_SOFT_FAIL\`s: reported, never verdict-driving.

| metric | margin | unit | binding | 8×SE at n=${d.rule.protocolGamesPerSurface} | basis |
| --- | ---: | --- | --- | ---: | --- |
${Object.entries(d.metrics).map(([m, v]) => `| \`${m}\` | ${v.margin} | ${v.unit} | ${v.binding} | ${v.noiseComponent ?? "n/a"} | ${v.basis} |`).join("\n")}

Noise basis: ${d.noiseBasis}.`);
  }

  if (has("candidate1-root-cause-analysis")) {
    const A = R("candidate1-root-cause-analysis"); const d = A.data;
    write("candidate1-root-cause-analysis.md", `${prov(A)}# Candidate 1 — root-cause analysis of the V4 substantive failures

No engine change before root-cause evidence exists. This document is that
evidence: ${d.rootCaused}/${d.substantiveFailures} substantive failures walked through the complete mechanic
chain, with factorial intervention cells (${d.gamesPerCell} games each, diagnostic seed
master \`${d.seedMaster}\`). Interventions are \`DIAGNOSTIC_ONLY\` profile clones —
never data, never a repair.

## Root-cause classes

| class | failures |
| --- | --- |
${Object.entries(d.rootCauseClasses).map(([k, v]) => `| \`${k}\` | ${v.join(", ")} |`).join("\n")}

## Dead team-intelligence channels (shared structural evidence)

Channels whose value is (near-)constant across every V4 fixture AND every era
reference — carrying no identity at all for calibration-built teams:

| channel | distinct values | dead |
| --- | --- | --- |
${Object.entries(d.deadTeamIntelligenceChannels).map(([k, v]) => `| \`${k}\` | ${v.distinctValues.slice(0, 6).join(", ")} | **${v.dead}** |`).join("\n")}

## Per-failure conclusions

${Object.values(d.conclusions).map((c) => `### ${c.failureId} — ${c.teamSeason} · \`${c.traitId}\` · \`${c.metricId}\`

**Root cause:** ${c.rootCause}

| chain stage | finding |
| --- | --- |
${Object.entries(c.chain).map(([k, v]) => `| ${k} | ${typeof v === "string" ? v.replace(/\|/g, "\\|") : "see artifact"} |`).join("\n")}

**Factorial cells:**

| cell | ${Object.keys(c.factorial[0]).filter((k) => !["label", "games", "invariantViolations"].includes(k)).join(" | ")} |
| --- | ${Object.keys(c.factorial[0]).filter((k) => !["label", "games", "invariantViolations"].includes(k)).map(() => "---:").join(" | ")} |
${c.factorial.map((f) => `| ${f.label} | ${Object.entries(f).filter(([k]) => !["label", "games", "invariantViolations"].includes(k)).map(([, v]) => v?.mean ?? "—").join(" | ")} |`).join("\n")}

**Repair direction:** ${c.repairDirection}
`).join("\n")}`);
  }

  if (has("candidate1-movement-repair")) {
    const A = R("candidate1-movement-repair"); const d = A.data;
    const M = has("candidate1-draft-manifest") ? R("candidate1-draft-manifest").data : null;
    write("candidate1-movement-repair.md", `${prov(A)}# Candidate 1 — movement & coach-saturation repair

**Acceptance gate: ${d.pass ? "PASS" : `FAIL (${d.failedGates.join(", ")})`}** — ${d.pairsPerCell * 2} games per cell.

Movement family: ${d.movementFamily.map((x) => `\`${x}\``).join(", ")} via \`${d.helper}\`.

| gate | result |
| --- | --- |
${Object.entries(d.gates).map(([k, v]) => `| ${k} | **${v ? "PASS" : "FAIL"}** |`).join("\n")}

## Coach differentiation (fixed roster: 1991-92 Bulls five)

| coach | movementShare | ppp |
| --- | ---: | ---: |
${d.coachDifferentiation.cells.map((c) => `| ${c.label} | ${c.movementShare.mean} | ${c.ppp.mean} |`).join("\n")}

## No efficiency guarantee

${d.noEfficiencyGuarantee.reading}: share +${d.noEfficiencyGuarantee.shareDiff.diff}, ppp ${d.noEfficiencyGuarantee.pppDiff.diff}.

## Era movement spread (no flattening)

| era | reference movementShare |
| --- | ---: |
${Object.entries(d.eraSpread.perEra).map(([e, v]) => `| ${e} | ${v} |`).join("\n")}

spread: **${fmt(d.eraSpread.spread)}**

## Zone continuity

${d.zoneContinuity.reading}.

| defensive coach | zone share |
| --- | ---: |
${d.zoneContinuity.cells.map((c) => `| ${c.coachId} | ${c.defensiveZoneShare.mean} |`).join("\n")}
${M ? `
## Candidate 1 draft

\`${M.candidateId}\` (${M.candidateSelectionStatus}/${M.candidateLockStatus}/${M.validationAttemptStatus}), parent \`${M.parentCandidateId}\`
core \`${M.parentCoreHash.slice(0, 16)}...\` → \`${M.coreHash.slice(0, 16)}...\` under closure builder ${M.closureBuilderVersion}.

Changed core files: ${M.changedCoreFiles.map((f) => `\`${f}\``).join(", ")}.

Closure correction: ${M.closureCorrection.defect} — ${M.closureCorrection.consequence}.` : ""}`);
  }

  if (has("candidate1-offense-repair")) {
    const A = R("candidate1-offense-repair"); const d = A.data;
    const B = has("calibration-shooting-backfill") ? R("calibration-shooting-backfill").data : null;
    write("candidate1-offense-repair.md", `${prov(A)}# Candidate 1 — offensive-identity repair

**Acceptance gate: ${d.pass ? "PASS" : `FAIL (${d.failedGates.join(", ")})`}** — ${d.pairsPerCell * 2} games per cell.

Adapter INPUT_QUALITY_COMPRESSION repair: volume reads points per game alongside
FGA; efficiency reads TS% or a labelled FG%/FT% estimate centred on the store
population median; the interior diet comes from the two-point split or the
documented three-point volume; post threat falls back to recorded total boards.

**Share-proxy protection (frozen before measurement):** bound ${d.shareProxyProtection.bound}
(baseline ${d.shareProxyProtection.baselineMeanComposite} × ${d.shareProxyProtection.maxRegressionFactor}); measured mean composite **${d.meanCompositeShareMae}**.

| gate | result |
| --- | --- |
${Object.entries(d.gates).map(([k, v]) => `| ${k} | **${v ? "PASS" : "FAIL"}** |`).join("\n")}

## Cells (subject ppp vs live reference self-baseline)

| fixture | class | ppp | ref self | diff | share MAE |
| --- | --- | ---: | ---: | ---: | ---: |
${[...d.v4EliteOffense.map((c) => [c, "V4 elite"]), ...d.heldInEliteOffense.map((c) => [c, "held-in elite"]), ...d.medianTeams.map((c) => [c, "non-elite"])].map(([c, k]) => `| ${c.fixtureId} | ${k} | ${c.ppp.mean} | ${c.refSelfPpp} | ${c.diff.diff} | ${c.compositeShareMae} |`).join("\n")}

Non-elite population mean diff: **${d.nonElitePopulationMeanDiff}** (no universal scoring shift).

## v4f-02 (Spurs) decomposition — \`${d.spursDecomposition.disposition}\`

As-is diff ${d.spursDecomposition.asIsDiff}. Imputing the store era-median FG%
(${d.spursDecomposition.storeEraMedianFgPct}) to the ${d.spursDecomposition.nullShootingPlayers} null-shooting Spurs closes only
**${d.spursDecomposition.imputationCloses}** — the remainder is the reference: ${d.spursDecomposition.referenceFive}.

V5 action: ${d.spursDecomposition.v5Action}.
${B ? `
## Shooting backfill

${B.profilesBackfilled} profiles filled from player career tables (team-verified, null fields only);
${B.sourceLacksCareerTable} recorded \`SOURCE_LACKS_CAREER_TABLE\` — the authorized source carries no
career statistics for them, and the nulls stand rather than being estimated around.

| player | season | outcome | filled |
| --- | --- | --- | --- |
${B.results.map((r) => `| ${r.name} | ${r.season} | ${r.outcome} | ${r.filled.map((f) => `${f.field}=${f.value}`).join(", ") || "—"} |`).join("\n")}` : ""}`);
  }

  if (has("candidate1-defense-repair")) {
    const A = R("candidate1-defense-repair"); const d = A.data;
    const B = has("defensive-accolades") ? R("defensive-accolades").data : null;
    write("candidate1-defense-repair.md", `${prov(A)}# Candidate 1 — defensive-identity repair

**Acceptance gate: ${d.pass ? "PASS" : `FAIL (${d.failedGates.join(", ")})`}** — ${d.pairsPerCell * 2} games per cell.

DEFENSIVE_PROXY_INVERSION repair: documented same-season defensive accolades
(per-season award pages, never recall) become position-scoped FLOORS on the
containment channels in every era. Steals and blocks measure gambling, not
containment.

| gate | result |
| --- | --- |
${Object.entries(d.gates).map(([k, v]) => `| ${k} | **${v ? "PASS" : "FAIL"}** |`).join("\n")}

## Cells (reference ppp vs the team, against the reference self-baseline)

| fixture | class | ref-vs-team | ref self | diff | prior V4 diff |
| --- | --- | ---: | ---: | ---: | ---: |
${[...d.v4EliteDefense.map((c) => [c, "V4 elite D"]), ...d.heldInEliteDefense.map((c) => [c, "held-in elite D"]), ...d.nonEliteTeams.map((c) => [c, "non-elite"])].map(([c, k]) => `| ${c.fixtureId} | ${k} | ${c.refPppVsTeam.mean} | ${c.refSelfPpp} | ${c.diff.diff} | ${d.priorV4Deficits[c.fixtureId] ?? "—"} |`).join("\n")}

Non-elite population mean diff **${d.nonElitePopulationMeanDiff}**; share proxy ${d.meanCompositeShareMae} (bound ${d.shareProxyProtection.bound}).

## Residual decomposition — \`${d.decomposition.disposition}\`

${d.decomposition.mechanismCapacity}.

Accolade coverage: ${Object.entries(d.decomposition.accoladeCoverage).map(([k, v]) => `${k}: ${v.flooredPlayers}/5`).join(" · ")}.

${d.decomposition.residualCauses.map((r) => `- ${r}`).join("\n")}

V5 action: ${d.decomposition.v5Action}.
${B ? `
## Accolade extraction

${B.profilesStamped} profiles stamped from ${B.allDefensiveSeasonsParsed} All-Defensive seasons and ${B.dpoySeasonsParsed} DPOY seasons. ${B.discipline}.` : ""}`);
  }

  if (has("candidate1-remaining-repairs")) {
    const A = R("candidate1-remaining-repairs"); const d = A.data;
    write("candidate1-remaining-repairs.md", `${prov(A)}# Candidate 1 — remaining repairs

**Acceptance gate: ${d.pass ? "PASS" : `FAIL (${d.failedGates.join(", ")})`}**. Unresolved substantive failures: **${d.unresolvedSubstantiveFailures}**.

## v4f-05 — offensive-glass wire (\`${d.orebRepair.disposition}\`)

${d.orebRepair.mechanism}.

| measure | value |
| --- | ---: |
| Sonics orebRate | ${d.orebRepair.teamOreb.mean} |
| reference self orebRate | ${d.orebRepair.refSelfOreb.mean} |
| diff | ${d.orebRepair.diff.diff} |
| prior V4 diff | ${d.orebRepair.priorV4Diff} |
| offensiveGlass as-is | ${d.orebRepair.saturationDiagnostic.offensiveGlassAsIs} |
| offensiveGlass with imputed oreb split | ${d.orebRepair.saturationDiagnostic.offensiveGlassWithImputedSplit} |
| reference offensiveGlass | ${d.orebRepair.saturationDiagnostic.referenceOffensiveGlass} |

V5 action: ${d.orebRepair.v5Action}.

## Era offensive-rebound rates (plausibility band)

| era | orebRate |
| --- | ---: |
${Object.entries(d.eraOrebRates).map(([e, v]) => `| ${e} | ${v} |`).join("\n")}

## Practical-margin-only failures — dispositions

| id | trait | team-season | diff | engine changed | under prospective policy |
| --- | --- | --- | ---: | --- | --- |
${d.marginOnlyDispositions.map((m) => `| \`${m.failureId}\` | \`${m.traitId}\` | ${m.teamSeason} | ${fmt(m.difference)} | **${m.engineChanged}** | \`${m.underProspectivePolicy}\` |`).join("\n")}`);
  }

  if (has("candidate1-internal-validation")) {
    const A = R("candidate1-internal-validation"); const d = A.data;
    const S = has("candidate1-side-symmetry") ? R("candidate1-side-symmetry").data : null;
    const P = has("candidate1-probability-validation") ? R("candidate1-probability-validation").data : null;
    const C = has("candidate1-competition-validation") ? R("candidate1-competition-validation").data : null;
    const M = has("candidate1-vs-candidate0") ? R("candidate1-vs-candidate0").data : null;
    write("candidate1-internal-validation.md", `${prov(A)}# Candidate 1 — internal validation

**${d.pass ? "PASS" : `FAIL (${d.failedGates.join(", ")})`}** at core \`${d.coreHash.slice(0, 16)}...\`

| gate | result |
| --- | --- |
${Object.entries(d.gates).map(([k, v]) => `| ${k} | **${v ? "PASS" : "FAIL"}** |`).join("\n")}

- calibration objective: tuning MAE ${d.calibrationObjective.tuningMae} (C0 ${d.calibrationObjective.candidate0.tuningMae}) · validation ${d.calibrationObjective.validationMae} (C0 ${d.calibrationObjective.candidate0.validationMae})
- statistical tails: ${d.statisticalTails.games} games, ${d.statisticalTails.invariantViolations} violations, ${d.statisticalTails.impossibleScores} impossible scores, p50 ${d.statisticalTails.scoreP50}
- replay exact: ${d.replay.exact} · ${d.replay.gamesPerSecond} games/sec
- synthetic development v2: ${d.syntheticDevelopmentV2.games} games, ${d.syntheticDevelopmentV2.invariantViolations} violations · stress set sealed
- hierarchy: strong beats weak ${d.hierarchy.strongWinRate} over ${d.hierarchy.pairedGames} paired games
${S ? `
## Side symmetry — ${S.pass ? "PASS" : "FAIL"}

${S.totalGames} paired games across ${S.cells} cells: gold advantage ${S.goldAdvantagePp}pp
(CI ${S.ci95Pp.lower}pp .. ${S.ci95Pp.upper}pp), systematic t=${S.systematic.tStatistic},
${S.cellsBeyondPracticalEffect} cells beyond ±${S.policy.perCellPracticalEffectPp}pp, ${S.bhSignificantCells} BH-significant, ${S.invariantViolations} violations.` : ""}
${P ? `
## Probability — ${P.pass ? "PASS" : "FAIL"}

Log loss ${P.regressionVsCandidate0.logLoss.c1} (C0 ${P.regressionVsCandidate0.logLoss.c0}, Δ ${P.materialRegression.logLossDelta}, bound ${P.materialRegression.bound});
achievable skill ${P.regressionVsCandidate0.fractionOfAchievableSkill.c1} (C0 ${P.regressionVsCandidate0.fractionOfAchievableSkill.c0});
ECE ${P.regressionVsCandidate0.ece.c1} (C0 ${P.regressionVsCandidate0.ece.c0});
max per-cell side bias ${P.regressionVsCandidate0.maxPerCellSideBias.c1} (C0 ${P.regressionVsCandidate0.maxPerCellSideBias.c0}). Every gate passes.` : ""}
${C ? `
## Competition modes — ${C.pass ? "PASS" : "FAIL"}

| mode | games | violations | detail |
| --- | ---: | ---: | --- |
${C.modes.map((m) => `| ${m.mode} | ${m.games} | ${m.invariantViolations} | ${m.series ? `${m.series} series, mean length ${m.meanLength}` : m.seasons ? `${m.seasons} seasons${m.meanWins ? `, mean wins ${m.meanWins}` : ""}${m.meanGoldWins ? `, mean gold wins ${m.meanGoldWins}` : ""}` : m.brackets ? `${m.brackets} brackets` : ""} |`).join("\n")}` : ""}
${M ? `
## Candidate 1 vs Candidate 0

Parent \`${M.parent.coreHash.slice(0, 16)}...\` (${M.parent.files} files, builder ${M.parent.closureBuilderVersion}) →
\`${M.candidate.coreHash.slice(0, 16)}...\` (${M.candidate.files} files, builder ${M.candidate.closureBuilderVersion}).
${M.changedFiles.length} changed: ${M.changedFiles.map((f) => `\`${f}\``).join(", ")}.
Parameter delta: ${M.parameterDelta}. ${M.behaviourDelta}.` : ""}`);
  }

  if (has("candidate1-lock")) {
    const A = R("candidate1-lock"); const d = A.data;
    write("candidate1-lock.md", `${prov(A)}# Candidate 1 — lock manifest

**\`${d.candidateId}\` · ${d.candidateSelectionStatus} / ${d.candidateLockStatus} / ${d.calibrationStatus} · validation attempt ${d.validationAttemptStatus}**

Scope: ${d.scope}

| fact | value |
| --- | --- |
| possessionCalibrationVersion | \`${d.possessionCalibrationVersion}\` |
| parent candidate | \`${d.parentCandidateId}\` (\`${d.parentLockManifest}\`) |
| parent core hash | \`${d.parentCoreHash}\` |
| core hash | \`${d.coreHash}\` |
| validated core hash | \`${d.validatedCoreHash}\` |
| parameter set hash | \`${d.parameterSetHash}\` (parameter changes: ${d.parameterChanges}) |
| core files | ${d.coreFileCount} (closure builder ${d.closureBuilderVersion}) |
| lock blockers | ${d.candidateLockBlockers.length} |
| all engineering gates pass | **${d.allEngineeringGatesPass}** |
| manifest hash | \`${d.manifestHash}\` |
| locked at commit | \`${d.lockedAtCommit}\` |

**Stamp isolation.** ${d.stampIsolation}

**Changed core files.** ${d.changedCoreFiles.map((f) => `\`${f}\``).join(", ")}

**Formal holdout access counts at lock time.** V3 ${d.formalHoldoutAccessCounts.historicalHoldoutV3} · V4 ${d.formalHoldoutAccessCounts.historicalHoldoutV4} · synthetic stress ${d.formalHoldoutAccessCounts.syntheticStressHoldoutV2}.

**Not claimed.** ${d.notClaimed.map((x) => `\`${x}\``).join(", ")}.

**Post-lock mutation policy.** ${d.postLockMutationPolicy}`);
  }

  console.log(written.length ? written.join("\n") : "no 6c4a artifacts yet");
}
