#!/usr/bin/env node
// ── Render Phase 6C4A documents from artifacts ──────────────────────────────
//   npm run c1:report
// Formats only. Never sums, counts, averages or derives. Renders whichever
// 6C4A artifacts exist, so it can run after every workstream.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt } from "../../src/v3/calibration/artifacts.js";
import { DIR } from "./failureRegister.mjs";

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const has = (n) => artifactExists(n, DIR);
const R = (n) => readArtifact(n, DIR);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run c1:report  from: ${a.generationCommand} -->\n`;

if (import.meta.url === `file://${process.argv[1]}`) {
  if (has("historical-v4-failure-register")) {
    const A = R("historical-v4-failure-register"); const d = A.data;
    write("historical-v4-failure-register.md", `${prov(A)}# Historical Holdout V4 — failure register

Every hard failure from the formal V4 run, read directly from
\`historical-holdout-v4-results.json\` (never from prose), classified exactly once.
The set is a consumed \`FAILED_HOLDOUT_DIAGNOSTIC_SET\`: usable for development,
never rescored, never a fresh holdout.

- hard failures in the verdict: **${d.hardFailuresInVerdict}**
- failures registered: **${d.failuresRegistered}** (reconciles: **${d.reconciles}**)
- substantive (engine change required): **${d.substantiveCount}**
- practical-margin-only (engine change prohibited): **${d.byCategory.PRACTICAL_MARGIN_ONLY}**

| category | count |
| --- | ---: |
${Object.entries(d.byCategory).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

## Register

| id | team-season | trait | metric | diff | z | category |
| --- | --- | --- | --- | ---: | ---: | --- |
${d.failures.map((f) => `| \`${f.failureId}\` | ${f.teamSeason} | \`${f.traitId}\` | \`${f.metricId}\` | ${fmt(f.difference)} | ${fmt(f.z)} | \`${f.category}\` |`).join("\n")}

## Practical-margin-only artifacts

These four failed the frozen V4 rule (sign + CI excluding zero, no practical
margin). Their magnitudes fall below any justifiable practical margin, so the
correct repair is to the validation policy — prospectively — not to the engine.

| id | trait | team-season | diff | engine change | policy change |
| --- | --- | --- | ---: | --- | --- |
${d.marginArtifacts.map((m) => `| \`${m.failureId}\` | \`${m.traitId}\` | ${m.teamSeason} | ${fmt(m.difference)} | **${m.ENGINE_CHANGE_REQUIRED}** | **${m.POLICY_V3_CHANGE_REQUIRED}** |`).join("\n")}

## Substantive failures — repair scaffolding

| id | team-season | metric | suspected mechanic | acceptance |
| --- | --- | --- | --- | --- |
${d.registerDetail.map((f) => `| \`${f.failureId}\` | ${f.teamSeason} | \`${f.metricId}\` | ${f.suspectedMechanic} | ${f.candidateAcceptanceCriteria} |`).join("\n")}

Every substantive failure's mechanic chain: \`trait → source inputs → player
intelligence → team intelligence → coach deployment → raw action weights →
normalized weights → reachability → conditional outcomes → game metric\`.
No engine change before root-cause evidence exists.`);
  }

  if (has("candidate0-preservation")) {
    const A = R("candidate0-preservation"); const d = A.data;
    write("candidate0-preservation.md", `${prov(A)}# Candidate 0 preservation — Phase 6C4A

Candidate 1 is a **separate candidate**. Candidate 0 is never mutated; it
replays exactly from the commit recorded here.

| fact | value |
| --- | --- |
| candidate | \`${d.candidate0.candidateId}\` — SELECTED / LOCKED |
| core hash | \`${d.candidate0.coreHash}\` |
| parameter set hash | \`${d.candidate0.parameterSetHash}\` |
| possessionCalibrationVersion | \`${d.candidate0.possessionCalibrationVersion}\` |
| behaviour snapshot | \`${d.candidate0.behaviourSnapshotHash}\` |
| production engine source sha256 | \`${d.candidate0.productionEngineSha256}\` |
| git commit before Candidate 1 | \`${d.candidate0.gitCommitBeforeCandidate1}\` |

${d.candidate0.replayGuarantee}.

| preserved verdict | status | access count |
| --- | --- | ---: |
| Historical V3 | \`${d.historicalV3.verdict}\` | ${d.historicalV3.accessCount} |
| Historical V4 | \`${d.historicalV4.verdict}\` → \`${d.historicalV4.setStatus}\` | ${d.historicalV4.accessCount} |
| Synthetic V2 | \`${d.syntheticV2.status}\` | ${d.syntheticV2.accessCount} |`);
  }

  console.log(written.length ? written.join("\n") : "no 6c4a artifacts yet");
}
