#!/usr/bin/env node
// ── Render Phase 6C3R documents from artifacts ──────────────────────────────
//   npm run validation:6c3r:report
// Formats only. Never sums, counts, averages or derives. Renders whichever
// 6C3R artifacts exist, so it can run after every workstream.
import { writeFileSync, mkdirSync } from "node:fs";
import { readArtifact, artifactExists, fmt, countsTable } from "../../src/v3/calibration/artifacts.js";

const DIR = "data/validation/6c3r";
const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const has = (n) => artifactExists(n, DIR);
const R = (n) => readArtifact(n, DIR);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run validation:6c3r:report  from: ${a.generationCommand} -->\n`;

if (import.meta.url === `file://${process.argv[1]}`) {
  if (has("historical-v3-failure-diagnosis")) {
    const A = R("historical-v3-failure-diagnosis"); const d = A.data;
    const P = R("historical-v3-preservation-manifest").data;
    write("historical-holdout-v3-failure-diagnosis.md", `${prov(A)}# Historical Holdout V3 — failure diagnosis

**Formal verdict: \`${d.formalVerdict}\` — preserved permanently and never rescored.**

| Claim | Established |
| --- | --- |
| candidate performance failure | **${d.candidatePerformanceFailureEstablished}** |
| validation-surface failure | **${d.validationSurfaceFailureEstablished}** |
| failure class | \`${d.failureClass}\` |
| replacement validation required | **${d.replacementValidationRequired}** |

${d.evidenceBasis}

## The surface

${d.surface.design}

${d.surface.algebraicDependence} Measured maximum separation across the eight
fixtures: **${fmt(d.surface.maxSeparationAcrossFixtures, 5)}** points per possession.

${d.surface.contradiction}

## Traits

- scored: **${fmt(d.traits.scored, 0)}**
- failed on mirror-ambiguous metrics: **${fmt(d.traits.failedOnMirrorAmbiguousMetrics, 0)}**
- failed on metrics the surface could decide: **${fmt(d.traits.failedOnObservableMetrics, 0)}**
- ${d.traits.vocabularyCoverage}

| Fixture | Trait | Metric | Observed | Reference median |
| --- | --- | --- | --- | --- |
${d.traits.mirrorAmbiguousFailures.map((t) => `| \`${t.fixtureId}\` | ${t.trait} | \`${t.metric}\` | ${fmt(t.observed, 5)} | ${fmt(t.referenceMedian, 5)} |`).join("\n")}

## What V3 did establish

**Quantitative.** ${d.whatV3DidEstablish.quantitative}

**Structural.** ${d.whatV3DidEstablish.structural}

## Why the verdict remains FAIL

${d.whyTheVerdictRemainsFail}

## Why Candidate 0 remains locked

${d.whyCandidateZeroRemainsLocked}

## Why a replacement holdout is required

${d.whyAReplacementHoldoutIsRequired}

## Preservation

| Field | Value |
| --- | --- |
| state | ${P.state} |
| access count | ${fmt(P.accessCount, 0)} |
| run hash | \`${P.runHash}\` |
| results file sha256 | \`${P.resultsFileSha256}\` |
| verdict file sha256 | \`${P.verdictFileSha256}\` |
| access log sha256 | \`${P.accessLogSha256}\` |
| verdict hash | \`${P.verdictHash}\` |

${P.mutationRule}
`);
  }

  if (has("historical-trait-registry")) {
    const A = R("historical-trait-registry"); const d = A.data;
    write("historical-trait-observability.md", `${prov(A)}# Historical trait observability

Every trait in the historical identity vocabulary, classified for the
opponent-paired + era-reference measurement surface. A trait may contribute to a
verdict only when it is observable, and an unobservable trait is excluded before
the holdout opens rather than becoming a failure inside it.

- vocabulary traits: **${fmt(d.counts.total, 0)}**

${countsTable(d.counts.byClass, { header: "Observability class" })}

${countsTable(d.counts.byFamily, { header: "Trait family" })}

## Scoring-eligible traits (${fmt(d.counts.scoringEligible, 0)})

| Trait | Family | Class | Primary metric | Direction | Surface |
| --- | --- | --- | --- | --- | --- |
${d.traits.filter((t) => t.scoringEligibility).map((t) => `| \`${t.traitId}\` | ${t.traitFamily} | ${t.observabilityClass} | \`${t.primaryMetrics[0]}\` | ${t.expectedDirection} | ${t.requiredMeasurementSurface} |`).join("\n")}

## Unobservable on this surface (${fmt(d.counts.byClass.UNOBSERVABLE_ON_THIS_SURFACE ?? 0, 0)})

| Trait | Why |
| --- | --- |
${d.traits.filter((t) => t.observabilityClass === "UNOBSERVABLE_ON_THIS_SURFACE").map((t) => `| \`${t.traitId}\` | ${t.definition} |`).join("\n")}
`);
  }

  if (has("metric-dependency-graph")) {
    const A = R("metric-dependency-graph"); const d = A.data;
    write("metric-dependency-graph.md", `${prov(A)}# Metric dependency graph

Detects metric pairs a single surface cannot independently identify, and
hard-fails any rubric that scores contradictory expectations on them.

- metrics: **${fmt(d.metrics.length, 0)}**
- dependency groups: **${fmt(d.dependencyGroups.length, 0)}**
- contradictory dependent rules detected in the frozen rubric: **${fmt(d.contradictionsInRubric.length, 0)}**

## Dependency groups

| Group | Members | Kind | Surface restriction |
| --- | --- | --- | --- |
${d.dependencyGroups.map((g) => `| ${g.id} | ${g.members.map((m) => `\`${m}\``).join(", ")} | ${g.kind} | ${g.restriction} |`).join("\n")}

## The V3 lesson, encoded

${d.mirrorRule}
`);
  }

  console.log(`RENDERED ${written.length} document(s)`);
  for (const p of written) console.log(`  ${p}`);
}
