#!/usr/bin/env node
// ── Render the Phase 6C3 documents from artifacts ───────────────────────────
//   npm run validation:report
// Formats only. Never sums, counts, averages or derives.
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { readArtifact, artifactExists, fmt, countsTable, ARTIFACT_DIR_6C3 } from "../../src/v3/calibration/artifacts.js";

const DOCS = "docs/simulation-v3";
mkdirSync(DOCS, { recursive: true });
const R = (n) => readArtifact(n, ARTIFACT_DIR_6C3);
const written = [];
const write = (n, b) => { writeFileSync(`${DOCS}/${n}`, `${b.trimEnd()}\n`); written.push(`${DOCS}/${n}`); };
const prov = (a) => `<!-- RENDERED FROM ARTIFACT — do not edit by hand. -->\n<!-- source: ${a.artifact}.json  outputHash: ${a.outputHash} -->\n<!-- generated by: npm run validation:report  from: ${a.generationCommand} -->\n`;

if (import.meta.url === `file://${process.argv[1]}`) {
  // ── preflight ─────────────────────────────────────────────────────────────
  {
    const A = R("phase6c3-preflight"); const d = A.data;
    const c = d.supportedScopeCensus;
    write("phase-6c3-preflight.md", `${prov(A)}# Phase 6C3 preflight

- \`formalValidationMayBegin\`: **${d.formalValidationMayBegin}**
- failed gates: ${d.failedGates.length ? d.failedGates.join(", ") : "none"}

## Locked candidate

| Field | Value |
| --- | --- |
${Object.entries(d.lockedCandidate).map(([k, v]) => `| \`${k}\` | \`${v}\` |`).join("\n")}

## Candidate core

- files in the closure: **${fmt(d.candidateCore.fileCount, 0)}**
- \`aggregateCoreHash\`: \`${d.candidateCore.aggregateCoreHash}\`
- missing: ${d.candidateCore.missing.length ? d.candidateCore.missing.join(", ") : "none"}

## Seals

| Set | Access count | Status |
| --- | --- | --- |
| historical holdout v3 | ${fmt(d.holdoutAccessCounts.historicalHoldoutV3, 0)} | ${d.seals["historical-holdout-v3"].status} |
| synthetic stress holdout v2 | ${fmt(d.holdoutAccessCounts.syntheticStressHoldoutV2, 0)} | ${d.seals["synthetic-stress-holdout-v2"].status} |

Independent leakage check: ${fmt(d.sealedFixtureLeakage.checked, 0)} sealed ids checked across
${d.sealedFixtureLeakage.dirsChecked.map((x) => `\`${x}\``).join(", ")} — **${fmt(d.sealedFixtureLeakage.leaks.length, 0)}** leaks.

## Policies

| Policy | Version | Hash |
| --- | --- | --- |
| holdout acceptance | ${d.policies.holdoutAcceptancePolicyVersion} | \`${d.policies.acceptancePolicyHash}\` |
| holdout supported scope | ${d.policies.holdoutSupportedScopeVersion} | \`${d.policies.supportedScopePolicyHash}\` |

- ratio gate: ${fmt(d.policies.maxHoldoutToInternalCompositeRatio, 2)}
- minimum games per fixture: ${fmt(d.policies.minGamesPerHoldoutFixture, 0)}
- maximum openings per set: ${fmt(d.policies.maxOpeningsPerSet, 0)}

## Supported scope, measured before opening anything

${fmt(c.teamFieldCells, 0)} team-level target cells across 8 fixtures.

${countsTable(c.byClass, { header: "Support class" })}

- proxy share maps available: **${fmt(c.proxyShareMapsAvailable, 0)}** of ${fmt(c.proxyShareMapsPossible, 0)}
- fixtures with no numeric surface: ${c.fixturesWithNoNumericSurface.length ? c.fixturesWithNoNumericSurface.map((x) => `\`${x}\``).join(", ") : "none"}
- eras covered: ${fmt(c.erasCovered.length, 0)}

${c.honestSummary}

| Fixture | Season | Era | Overall confidence | Proxy maps | Identity traits | Numeric surface |
| --- | --- | --- | --- | --- | --- | --- |
${c.perFixture.map((f) => `| \`${f.fixtureId}\` | ${f.season} | ${f.eraStyleId} | ${f.confidence?.overallFixtureConfidence ?? "—"} | ${fmt(f.supportedProxyCount, 0)}/5 | ${fmt(f.identityTraitCount, 0)} | ${f.hasAnyNumericSurface ? "yes" : "**no**"} |`).join("\n")}

## External preconditions

${d.externalPreconditionsUnmet.length ? d.externalPreconditionsUnmet.map((x) => `- ${x}`).join("\n") : "- all met"}

Treatment: \`${d.externalPreconditionTreatment}\`
`);
  }

  // ── acceptance policy ─────────────────────────────────────────────────────
  {
    const A = R("phase6c3-preflight"); const d = A.data;
    write("formal-holdout-acceptance-policy.md", `${prov(A)}# Formal holdout acceptance policy

Frozen before either holdout was opened, and pushed before the runner existed.

| Policy | Version | Hash |
| --- | --- | --- |
| holdout acceptance | ${d.policies.holdoutAcceptancePolicyVersion} | \`${d.policies.acceptancePolicyHash}\` |
| supported scope | ${d.policies.holdoutSupportedScopeVersion} | \`${d.policies.supportedScopePolicyHash}\` |

## What the policy may and may not inspect

It may inspect target availability, target confidence, metric counts, fixture
counts and era coverage. It may **not** inspect candidate holdout outputs,
errors, win rates or distributions. This policy was written from availability
alone, and no engine output on a holdout fixture existed when it was frozen.

## Quantitative gate

- holdout composite error / internal composite error must be at most **${fmt(d.policies.maxHoldoutToInternalCompositeRatio, 2)}**
- minimum **${fmt(d.policies.minGamesPerHoldoutFixture, 0)}** games per fixture
- a set may be opened at most **${fmt(d.policies.maxOpeningsPerSet, 0)}** time

## Exclusion rule

An UNAVAILABLE or NOT_APPLICABLE metric contributes no error term, no pass
credit and no failure. Zero-filling is forbidden: ${fmt(d.supportedScopeCensus.byClass.UNAVAILABLE ?? 0, 0)} of
${fmt(d.supportedScopeCensus.teamFieldCells, 0)} team-level cells are unavailable, and reading them as
observed zeros would produce a near-perfect score that measures nothing.
`);
  }

  // ── dry run ───────────────────────────────────────────────────────────────
  {
    const A = R("holdout-pipeline-dryrun"); const d = A.data;
    write("holdout-pipeline-dryrun.md", `${prov(A)}# Holdout pipeline dry run

${fmt(d.checksPassed, 0)} of ${fmt(d.checksTotal, 0)} checks pass. All pass: **${d.allPass}**.

${d.purpose}

Mock members (development fixtures, never a holdout id): ${d.mockMembers.map((x) => `\`${x}\``).join(", ")}

| Check | Verdict | Detail |
| --- | --- | --- |
${d.checks.map((c) => `| \`${c.name}\` | ${c.pass ? "OK" : "**FAIL**"} | ${c.detail} |`).join("\n")}

Real seals after the dry run: historical **${fmt(d.realSealsUntouched.historicalHoldoutV3, 0)}**,
synthetic **${fmt(d.realSealsUntouched.syntheticStressHoldoutV2, 0)}**.
`);
  }

  // ── reference baseline ────────────────────────────────────────────────────
  {
    const A = R("internal-reference-baseline"); const d = A.data;
    write("holdout-internal-reference-baseline.md", `${prov(A)}# Internal reference baseline

${d.purpose}

- computed from: ${d.computedFrom}
- sealed fixtures used: **${fmt(d.sealedFixturesUsed, 0)}**
- seed block: ${d.seedBlock}
- seeds per fixture: ${fmt(d.seedsPerFixture, 0)}
- \`referenceHash\`: \`${d.referenceHash}\`

## Composite share error

| Measure | Value |
| --- | --- |
| mean | ${fmt(d.baseline.internalCompositeMean, 5)} |
| median | ${fmt(d.baseline.internalCompositeMedian, 5)} |
| minimum | ${fmt(d.baseline.internalCompositeMin, 5)} |
| maximum | ${fmt(d.baseline.internalCompositeMax, 5)} |
| fixtures contributing | ${fmt(d.baseline.fixturesContributing, 0)} of ${fmt(d.baseline.fixturesTotal, 0)} |

## Per share metric

| Metric | Fixtures | Mean | Median |
| --- | --- | --- | --- |
${Object.entries(d.baseline.perMetric).map(([k, v]) => `| \`${k}\` | ${fmt(v.fixtures, 0)} | ${fmt(v.mean, 5)} | ${fmt(v.median, 5)} |`).join("\n")}

## Reference medians for the identity rubric

| Metric | Median |
| --- | --- |
${Object.entries(d.referenceMedians).map(([k, v]) => `| \`${k}\` | ${fmt(v, 5)} |`).join("\n")}
`);
  }

  // ── historical holdout ────────────────────────────────────────────────────
  {
    const A = R("historical-holdout-results"); const d = A.data;
    write("historical-holdout-validation.md", `${prov(A)}# Historical holdout v3 validation

**Verdict: ${d.verdict}.**

## Access

| Field | Value |
| --- | --- |
| set | \`${d.set}\` |
| access count before | ${fmt(d.accessCountBefore, 0)} |
| access count after | **${fmt(d.accessCountAfter, 0)}** |
| operator | ${d.accessEvent.actor} |
| reason | ${d.accessEvent.reason} |
| opened at commit | \`${d.accessEvent.openedAtCommit}\` |
| run status | ${d.runStatus} |
| run hash | \`${d.runHash}\` |

## Identity of what was tested

| Field | Value |
| --- | --- |
${Object.entries(d.identity).map(([k, v]) => `| \`${k}\` | \`${v}\` |`).join("\n")}

## Volume

${fmt(d.fixturesEvaluated, 0)} fixtures, ${fmt(d.gamesPerFixture, 0)} games each, **${fmt(d.totalGames, 0)}** games.
Eras covered: ${d.erasCovered.join(", ")}.

## Supported scope

${countsTable(d.supportedScope.teamFieldClassTotals, { header: "Team-field class" })}

- proxy share maps scored: **${fmt(d.supportedScope.proxyShareMapsScored, 0)}** of ${fmt(d.supportedScope.proxyShareMapsPossible, 0)}
- identity traits scored: ${fmt(d.supportedScope.identityTraitsScored, 0)} · unscored: ${fmt(d.supportedScope.identityTraitsUnscored, 0)}
- fixtures without a numeric surface: ${d.supportedScope.fixturesWithoutNumericSurface.length ? d.supportedScope.fixturesWithoutNumericSurface.map((x) => `\`${x}\``).join(", ") : "none"}
- zero-fill used: **${d.supportedScope.zeroFillUsed}**

${d.supportedScope.exclusionRule}

## Quantitative generalisation

| Measure | Value |
| --- | --- |
| internal composite MAE | ${fmt(d.internalBaseline.mean, 5)} |
| holdout composite MAE | ${fmt(d.holdoutComposite, 5)} |
| ratio | **${fmt(d.holdoutToInternalRatio, 5)}** |
| frozen gate | <= ${fmt(d.ratioGate, 2)} |
| catastrophic threshold | ${fmt(d.catastrophicThreshold, 5)} |

Source of the denominator: ${d.internalBaseline.source}.

## Gates

| Gate | Verdict |
| --- | --- |
${Object.entries(d.gates).map(([k, v]) => `| \`${k}\` | ${v ? "PASS" : "**FAIL**"} |`).join("\n")}

## Per fixture

| Fixture | Era | Confidence | Composite MAE | Invariants | Ties | Replay | Opportunity | Era rules | Identity | Verdict |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${d.perFixture.map((f) => `| \`${f.fixtureId}\` | ${f.eraStyleId} | ${f.overallConfidence ?? "—"} | ${f.compositeMae == null ? "no numeric surface" : fmt(f.compositeMae, 5)} | ${f.invariantsClean ? "clean" : "FAIL"} | ${f.noTies ? "0" : "FAIL"} | ${f.replayExact ? "exact" : "FAIL"} | ${f.opportunityOk ? "ok" : "FAIL"} | ${f.eraOk ? "ok" : "FAIL"} | ${f.identityOk ? "ok" : "**FAIL**"} | ${f.pass ? "PASS" : "**FAIL**"} |`).join("\n")}

### Failure reasons

${d.perFixture.filter((f) => !f.pass).map((f) => `- \`${f.fixtureId}\`: ${f.failureReasons.join("; ")}`).join("\n") || "- none"}

## Per-fixture share detail

${d.results.map((r) => `### \`${r.fixtureId}\` — ${r.teamName} ${r.season} (${r.eraStyleId})

- composite MAE: ${r.compositeMae == null ? "no numeric surface" : fmt(r.compositeMae, 5)}
- supported share metrics: ${r.supportedShareMetrics.length ? r.supportedShareMetrics.map((x) => `\`${x}\``).join(", ") : "none"}
- unsupported: ${r.unsupportedShareMetrics.map((u) => `\`${u.metric}\` (${u.reason})`).join(", ") || "none"}
- possessions ${fmt(r.structural.meanPossessions, 2)} · points ${fmt(r.structural.meanPoints, 2)} · PPP ${fmt(r.structural.pointsPerPossession, 5)} · opponent PPP ${fmt(r.structural.opponentPointsPerPossession, 5)}
- top-option share ${fmt(r.structural.meanTopOptionShare, 5)} (within bounds: ${r.structural.topOptionShareWithinBounds})
- three-point attempts in a pre-three era: ${r.structural.threePointAttemptsInPreThreeEra ?? "n/a"}
- identity: ${fmt(r.identity.traitsPassed, 0)} of ${fmt(r.identity.traitsScored, 0)} scored traits passed, ${fmt(r.identity.traitsUnscored, 0)} unscored
- replay exact: ${r.replay.exact}`).join("\n\n")}
`);
  }

  // ── verdict ───────────────────────────────────────────────────────────────
  {
    const A = R("formal-holdout-verdict"); const d = A.data;
    write("formal-holdout-validation-report.md", `${prov(A)}# Formal holdout validation report

**Combined verdict: ${d.combinedVerdict}.**
**Calibration status: ${d.calibrationStatusAfterVerdict}.**
\`possessionCalibrationVersion\` remains ${d.possessionCalibrationVersion}.

\`verdictHash\`: \`${d.verdictHash}\`

## Holdout status

| Set | Verdict | Access count after |
| --- | --- | --- |
| historical holdout v3 | **${d.historicalHoldout.verdict}** | ${fmt(d.historicalHoldout.accessCountAfter, 0)} |
| synthetic stress holdout v2 | ${d.syntheticHoldout.verdict} | ${fmt(d.syntheticHoldout.accessCountAfter, 0)} |

${d.syntheticHoldout.notOpenedBecause ?? ""}

## Candidate immutability

| Field | Value |
| --- | --- |
| core hash at holdout | \`${d.candidateImmutability.coreHashAtHoldout}\` |
| core hash now | \`${d.candidateImmutability.coreHashNow}\` |
| core unchanged | **${d.candidateImmutability.coreUnchanged}** |
| parameter set hash | \`${d.candidateImmutability.parameterSetHash}\` |
| parameters unchanged | **${d.candidateImmutability.parameterUnchanged}** |
| parameter drift | ${d.candidateImmutability.parameterDrift.length ? d.candidateImmutability.parameterDrift.join(", ") : "none"} |
| parameter changes after holdout | ${fmt(d.candidateImmutability.parameterChangesAfterHoldout, 0)} |
| policy changes after holdout | ${fmt(d.candidateImmutability.policyChangesAfterHoldout, 0)} |
| post-holdout tuning | ${d.candidateImmutability.postHoldoutTuning} |

## What passed

**Quantitative generalisation gate: ${d.quantitative.gatePassed ? "PASSED" : "FAILED"}.**

| Measure | Value |
| --- | --- |
| internal composite MAE | ${fmt(d.quantitative.internalCompositeMae, 5)} |
| holdout composite MAE | ${fmt(d.quantitative.holdoutCompositeMae, 5)} |
| ratio | **${fmt(d.quantitative.ratio, 5)}** |
| frozen gate | <= ${fmt(d.quantitative.ratioGate, 2)} |

${d.quantitative.interpretation}

Structural gates passed (${fmt(d.quantitative.structuralGatesPassed.length, 0)}):
${d.quantitative.structuralGatesPassed.map((g) => `- \`${g}\``).join("\n")}

## What failed

Failed gates: ${d.diagnosis.failedGates.map((g) => `\`${g}\``).join(", ")}

${d.diagnosis.failingFixtures.map((f) => `- \`${f.fixtureId}\`: ${f.reasons.join("; ")}`).join("\n")}

### Diagnosis: \`${d.diagnosis.rootCause}\`

${d.diagnosis.explanation}

| Measure | Value |
| --- | --- |
| scored traits | ${fmt(d.diagnosis.scoredTraits, 0)} |
| failed on mirror-ambiguous metrics | **${fmt(d.diagnosis.traitsFailedOnMirrorAmbiguousMetrics, 0)}** |
| failed on metrics the surface can decide | ${fmt(d.diagnosis.traitsFailedOnValidMetrics, 0)} |
| max \`\|PPP - oppPPP\|\` across fixtures | ${fmt(d.diagnosis.maxPointsPerPossessionGapAcrossFixtures, 5)} |

Mirror-ambiguous failures:

| Fixture | Trait | Metric | Observed | Reference median |
| --- | --- | --- | --- | --- |
${d.diagnosis.mirrorAmbiguousFailures.map((t) => `| \`${t.fixtureId}\` | ${t.trait} | \`${t.metric}\` | ${fmt(t.observed, 5)} | ${fmt(t.referenceMedian, 5)} |`).join("\n")}

**What was not re-scored.** ${d.diagnosis.whatWasNotReScored}

**Why this is not downgraded to INVALID_RUN.** ${d.diagnosis.whyTheVerdictIsNotDowngradedToInvalidRun}

## Consequences

${d.consequences.map((c) => `- ${c}`).join("\n")}

## Replacement holdout

Required: **${d.replacementHoldoutRecommendation.required}**. ${d.replacementHoldoutRecommendation.why}

Before re-running:

${d.replacementHoldoutRecommendation.beforeReRunning.map((x, i) => `${i + 1}. ${x}`).join("\n")}

Candidate decision: ${d.replacementHoldoutRecommendation.candidateDecision}
`);
  }

  console.log(`RENDERED ${written.length} document(s)`);
  for (const p of written) console.log(`  ${p}`);
}
