import React, { useState } from 'react';
import { FRANCHISES, getFranchise, getFranchisePairing, getTonightGames, scheduleDateKey, franchiseDisplayName, SCHEDULE_METADATA } from '../franchises.js';
import { neutralTeamNaming, leagueCopy } from '../rights.js';
import { COACHES } from '../../v3/coaches.js';
import { ERA_STYLES } from '../../v3/eraStyles.js';
import { BY_ID, validateFive } from '../draft/model.js';
import FiveBuilder from '../components/FiveBuilder.jsx';
import ResultSummary from '../components/ResultSummary.jsx';
import PublicRecapNotice from '../components/PublicRecapNotice.jsx';
import useLoopAction from '../components/useLoopAction.js';

export default function FranchiseMode({ api, route, onResult }) {
  const query = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : new URLSearchParams();
  const pairing = getFranchisePairing(String(route || '').split('/')[3]);
  const initialGold = getFranchise(pairing?.goldId || query.get('gold')) || getFranchise('la-lakers');
  const initialBlue = getFranchise(pairing?.blueId || query.get('blue')) || getFranchise('boston');
  const [goldId, setGoldId] = useState(initialGold.id), [blueId, setBlueId] = useState(initialBlue.id), [entry, setEntry] = useState(query.get('entry') === 'control' ? 'control' : 'watch'), [ids, setIds] = useState([...initialGold.playerIds]), [coachId, setCoachId] = useState('neutral'), [eraId, setEraId] = useState('2020s'), [record, setRecord] = useState(null), [date, setDate] = useState(scheduleDateKey()), [tonightGame, setTonightGame] = useState(null);
  const { act, busy, error } = useLoopAction(api), gold = getFranchise(goldId), blue = getFranchise(blueId), neutral = neutralTeamNaming();
  const name = franchise => franchiseDisplayName(franchise, { neutralNaming: neutral });
  let tonight = []; try { tonight = getTonightGames(date); } catch { /* native date input can be empty while editing */ }
  const choosePairing = game => { setGoldId(game.homeId); setBlueId(game.awayId); setIds([...game.home.playerIds]); setEntry('watch'); setCoachId('neutral'); setEraId('2020s'); setTonightGame(game); setRecord(null); };
  const goldIds = entry === 'control' ? ids : gold.playerIds;
  const validation = validateFive(goldIds, { kind: 'any-five', allowOutOfPosition: false });
  const run = () => act({ op: 'play', mode: tonightGame ? 'tonight' : 'franchise', goldIds, blueIds: blue.playerIds, coachGoldId: entry === 'control' ? coachId : 'neutral', coachBlueId: 'neutral', eraId: entry === 'control' ? eraId : '2020s', franchiseGoldId: goldId, franchiseBlueId: blueId, ...(tonightGame ? { scheduleGameId: tonightGame.id, scheduleDate: date } : {}) }, data => { setRecord(data); onResult?.(data, { mode: tonightGame ? 'tonight' : 'franchise' }); });
  return <><h1>Franchise Clash</h1><p>Choose two curated all-time fives. Watch with automatic coaching, or take control of your five and an existing rules environment.</p><p className="loop-fine">These are documented proposals using the current player-decade pool, not official franchise rankings or a claim of complete career-affiliation coverage.</p>
    <div className="loop-toolbar"><label>Gold franchise<select aria-label="Gold franchise" value={goldId} disabled={busy} onChange={event => { setGoldId(event.target.value); setIds([...getFranchise(event.target.value).playerIds]); setTonightGame(null); }}>{FRANCHISES.map(f => <option key={f.id} value={f.id}>{name(f)}</option>)}</select></label><label>Blue franchise<select aria-label="Blue franchise" value={blueId} disabled={busy} onChange={event => { setBlueId(event.target.value); setTonightGame(null); }}>{FRANCHISES.map(f => <option key={f.id} value={f.id}>{name(f)}</option>)}</select></label><label>Entry<select aria-label="Entry" value={entry} disabled={busy} onChange={event => setEntry(event.target.value)}><option value="watch">Watch · automatic coaching</option><option value="control">Take control · choose your five and coach</option></select></label></div>
    {goldId === blueId && <p role="status" className="loop-error">Choose two different franchises for this matchup.</p>}
    {entry === 'watch' ? <div className="loop-grid">{[{ side: 'Gold', franchise: gold }, { side: 'Blue', franchise: blue }].map(({ side, franchise }) => <section className="loop-panel" key={side}><p className="loop-eyebrow">Team {side}</p><h2>{name(franchise)}</h2><ul className="loop-roster">{franchise.slots.map(slot => <li key={slot.pos}><span><strong>{slot.pos} · {BY_ID.get(slot.playerId)?.name}</strong><small>{BY_ID.get(slot.playerId)?.decade}</small></span></li>)}</ul><p className="loop-fine">{leagueCopy(franchise.notes)}</p></section>)}</div> : <><FiveBuilder value={ids} onChange={setIds} poolIds={gold.poolIds} allowOutOfPosition={false} disabled={busy} /><div className="loop-toolbar"><label>Your coach<select aria-label="Your coach" value={coachId} onChange={event => setCoachId(event.target.value)}><option value="neutral">League-Average Staff</option>{COACHES.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Rules environment<select aria-label="Rules environment" value={eraId} onChange={event => setEraId(event.target.value)}>{ERA_STYLES.map(e => <option key={e.id}>{e.id}</option>)}</select></label></div></>}
    <p className="loop-notice">{entry === 'watch' ? 'Automatic setup: League-Average Staff for both teams, 2020s rules. The existing possession simulation decides the game.' : 'Your player and coach selections change the existing game plan. The underlying simulation is unchanged.'}</p><PublicRecapNotice />
    <button type="button" className="loop-primary" disabled={busy || !validation.ok || goldId === blueId} onClick={run}>{busy ? 'Running the franchise matchup…' : entry === 'watch' ? 'Watch this matchup' : 'Play with my selections'}</button>{error && <p className="loop-error" role="alert">{error}</p>}<ResultSummary record={record} tag={tonightGame ? 'TONIGHT' : 'FRANCHISE'} onOpen={data => onResult?.(data, { mode: tonightGame ? 'tonight' : 'franchise' })} />
    <section className="loop-panel"><h2>Tonight’s Clash</h2><p>Scheduled pairings played by the all-time roster proposals above. The real game schedule does not turn this into a forecast.</p><label>Schedule date<input aria-label="Schedule date" type="date" value={date} onChange={event => { setDate(event.target.value); setTonightGame(null); }} /></label>{tonight.length ? <div className="loop-grid">{tonight.map(game => <article className="loop-mode-card" key={game.id || `${game.homeId}-${game.awayId}`}><h3>{name(game.home)} vs {name(game.away)}</h3><p>{game.tipoffET ? `${game.tipoffET} ET` : 'Start time: see the sourced schedule'}</p><button type="button" className="loop-secondary" onClick={() => choosePairing(game)}>Load this pairing</button>{game.pairing && <p><a className="loop-header-link" href={game.pairing.path}>Open pairing page</a></p>}</article>)}</div> : <p role="status">No listed games for this date in the sourced schedule snapshot.</p>}<p className="loop-fine">Schedule snapshot: {SCHEDULE_METADATA.season || '2026-27'}. Source changes require a new verified snapshot.</p></section>
  </>;
}
